Repository realm/realm-core, pull requests merged in 2018-09, with the labels that each got.

#3092 Release 5.10.0
  CHANGELOG.md
  dependencies.list
  tools/release-init.sh
Labels: T:Process

#3093 Exception Reform
  src/realm/alloc.cpp
  src/realm/array.cpp
  src/realm/array_basic_tpl.hpp
  src/realm/bptree.cpp
  src/realm/exceptions.cpp
  src/realm/exceptions.hpp
  src/realm/group.cpp
  src/realm/group_shared.cpp
  src/realm/impl/output_stream.cpp
  src/realm/impl/transact_log.cpp
  src/realm/query.cpp
  src/realm/query_expression.hpp
  src/realm/table.cpp
  src/realm/util/any.hpp
  src/realm/util/backtrace.cpp
  src/realm/util/backtrace.hpp
  src/realm/util/encrypted_file_mapping.cpp
  src/realm/util/file.cpp
  src/realm/util/file.hpp
  src/realm/util/file_mapper.cpp
  src/realm/util/interprocess_condvar.cpp
  src/realm/util/interprocess_mutex.hpp
  src/realm/util/optional.hpp
  src/realm/util/thread.cpp
  test/util/mem.cpp
  test/util/resource_limits.cpp
Labels: T:Internal

#3095 improved assert for File::unlock()
  src/realm/util/file.cpp
Labels: T:Internal

#3096 Fix an ABI compatibility issue
  src/realm/CMakeLists.txt
  tools/cmake/abitest/CMakeLists.txt
  tools/cmake/abitest/abimain.cpp
  tools/cmake/abitest/abitest.a
  tools/cmake/abitest/abitest.cpp
Labels: T:Internal

#3098 Build an arm64_32 slice for watchOS with Xcode 10
  CHANGELOG.md
  Jenkinsfile
  tools/cross_compile.sh
Labels: T:Enhancement
