Repository realm/realm-core, pull requests merged in 2018-07, with the labels that each got.

#3067 Improved scalability of slab allocator
  CHANGELOG.md
  src/realm/alloc.cpp
  src/realm/alloc.hpp
  src/realm/alloc_slab.cpp
  src/realm/alloc_slab.hpp
  src/realm/group.cpp
  test/test_destroy_guard.cpp
Labels: T:Enhancement

#3069 Prepare version 5.6.5
  CHANGELOG.md
  dependencies.list
Labels: T:Enhancement

#3074 Don't mark space as free in rollback() until we're actually done with it
  CHANGELOG.md
  src/realm/group_shared.hpp
Labels: T:Bug

#3078 Prepare release 5.7.2
  CHANGELOG.md
  dependencies.list
Labels: T:Internal
