Repository realm/realm-core, pull requests merged in 2018-08, with the labels that each got.

#3082 Fix undefined behaviour in the parser when serialising some unprintable chars
  CHANGELOG.md
  src/realm/util/serializer.cpp
  test/test_parser.cpp
Labels: T:Bug

#3080 Add build-time option REALM_DEBUG_EXTREME
  CMakeLists.txt
  src/realm/CMakeLists.txt
Labels: T:Internal

#3086 Prepare 5.8.0
  CHANGELOG.md
  dependencies.list
Labels: T:Feature

#3087 Record backtrace when throwing certain exceptions
  CHANGELOG.md
  src/realm/CMakeLists.txt
  src/realm/exceptions.cpp
  src/realm/exceptions.hpp
  src/realm/util/backtrace.cpp
  src/realm/util/backtrace.hpp
  src/realm/util/terminate.cpp
  test/CMakeLists.txt
  test/test_util_backtrace.cpp
Labels: T:Internal

#3089 Prepare version 5.9.0
  CHANGELOG.md
  dependencies.list
Labels: T:Enhancement

#3090 Add an optional output key to compact
  CHANGELOG.md
  src/realm/group_shared.cpp
  src/realm/group_shared.hpp
  test/test_shared.cpp
Labels: T:Enhancement

#3091 Version bump to 5.10.0
  CHANGELOG.md
  dependencies.list
  tools/release-init.sh
Labels: T:Internal
