Repository realm/realm-core, pull requests merged in 2018-10, with the labels that each got.

#3102 Fix incorrect results for sort/distinct over a link after a sort
  CHANGELOG.md
  src/realm/views.cpp
  src/realm/views.hpp
  test/test_query.cpp
Labels: T:Bug

#3104 Prepare version 5.10.3
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3106 Custom heap allocation interface
  CHANGELOG.md
  src/realm/CMakeLists.txt
  src/realm/util/allocator.cpp
  src/realm/util/allocator.hpp
  src/realm/util/buffer.hpp
  src/realm/util/string_buffer.cpp
  src/realm/util/string_buffer.hpp
  test/test_alloc.cpp
Labels: T:Internal

#3107 Prepare version 5.11.0
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3109 Avoid array placement new
  CHANGELOG.md
  src/realm/util/allocator.hpp
Labels: T:Bug-Crash

#3108 Dynamic allocator interface improvements
  CHANGELOG.md
  src/realm/util/allocator.hpp
  src/realm/util/buffer.hpp
  test/test_alloc.cpp
Labels: T:Internal

#3110 Release 5.11.1
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3113 Version bump to 5.11.2
  CHANGELOG.md
  dependencies.list
Labels: T:Process

#3114 Release/5.11.2
  CHANGELOG.md
  dependencies.list
Labels: T:Process

#3119 Remove the change log compatibility section
  CHANGELOG.md
  doc/CHANGELOG_template.md
Labels: T:Internal

#3115 Fixup: Don't overwrite stashes
  Jenkinsfile
Labels: T:Internal

#3120 assert to protect file integrity in case of corrupted freelist
  CHANGELOG.md
  src/realm/group_writer.cpp
Labels: T:Internal

#3121 prepare 5.11.3
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3124 REALM_NODISCARD macro
  src/realm/util/buffer.hpp
  src/realm/util/features.h
Labels: T:Internal

#3126 Optimize get free space size
  CHANGELOG.md
  src/realm/group.cpp
  src/realm/group.hpp
  src/realm/group_shared.cpp
  src/realm/group_writer.cpp
  src/realm/group_writer.hpp
  test/test_lang_bind_helper.cpp
Labels: T:Enhancement

#3128 Improve build process
  CHANGELOG.md
  CMakeLists.txt
  Jenkinsfile
  clang.Dockerfile
  dependencies.list
  generic.Dockerfile
  packaging/.gitignore
  packaging/centos-6/base-image/Dockerfile
  packaging/centos-6/build-image/inside/build-package
  packaging/centos-6/build-image/inside/docker-entrypoint.sh
  packaging/centos-6/test-image/Dockerfile
  packaging/centos-6/test-image/inside/test
  packaging/centos-7/base-image/Dockerfile
  packaging/centos-7/build-image/Dockerfile
  packaging/centos-7/build-image/inside/build-package
  packaging/centos-7/build-image/inside/docker-entrypoint.sh
  packaging/centos-7/test-image/Dockerfile
  packaging/centos-7/test-image/inside/test
  packaging/docker_build.sh
  packaging/functions.sh
  packaging/generic/base-image/Dockerfile
  packaging/generic/build-image/Dockerfile
  packaging/generic/build-image/inside/build-package
  packaging/generic/build-image/inside/docker-entrypoint.sh
  packaging/generic/test-image/Dockerfile
  packaging/generic/test-image/inside/test
  packaging/package.sh
  packaging/publish.groovy
  packaging/ubuntu-1604/base-image/Dockerfile
  packaging/ubuntu-1604/build-image/Dockerfile
  packaging/ubuntu-1604/build-image/inside/build-package
  packaging/ubuntu-1604/test-image/Dockerfile
  packaging/ubuntu-1604/test-image/inside/test
  src/realm/util/config.h.in
  tools/cmake/SpecialtyBuilds.cmake
Labels: T:Internal

#3130 STLAllocator: Fixups for GCC 4.9
  CHANGELOG.md
  src/realm/util/allocator.hpp
  test/test_alloc.cpp
Labels: T:Internal

#3129 Improve build process
  CHANGELOG.md
  CMakeLists.txt
  Jenkinsfile
  clang.Dockerfile
  generic.Dockerfile
  packaging/.gitignore
  packaging/centos-6/base-image/Dockerfile
  packaging/centos-6/build-image/inside/build-package
  packaging/centos-6/build-image/inside/docker-entrypoint.sh
  packaging/centos-6/test-image/Dockerfile
  packaging/centos-6/test-image/inside/test
  packaging/centos-7/base-image/Dockerfile
  packaging/centos-7/build-image/Dockerfile
  packaging/centos-7/build-image/inside/build-package
  packaging/centos-7/build-image/inside/docker-entrypoint.sh
  packaging/centos-7/test-image/Dockerfile
  packaging/centos-7/test-image/inside/test
  packaging/docker_build.sh
  packaging/functions.sh
  packaging/generic/base-image/Dockerfile
  packaging/generic/build-image/Dockerfile
  packaging/generic/build-image/inside/build-package
  packaging/generic/build-image/inside/docker-entrypoint.sh
  packaging/generic/test-image/Dockerfile
  packaging/generic/test-image/inside/test
  packaging/package.sh
  packaging/publish.groovy
  packaging/ubuntu-1604/base-image/Dockerfile
  packaging/ubuntu-1604/build-image/Dockerfile
  packaging/ubuntu-1604/build-image/inside/build-package
  packaging/ubuntu-1604/test-image/Dockerfile
  packaging/ubuntu-1604/test-image/inside/test
  src/realm/util/config.h.in
  tools/cmake/SpecialtyBuilds.cmake
Labels: T:Internal

#3131 get_database_path() const and public
  CHANGELOG.md
  src/realm/replication.cpp
  src/realm/replication.hpp
Labels: T:Internal

#3132 std::hash implementation for StringData
  src/realm/string_data.cpp
  src/realm/string_data.hpp
  test/test_string_data.cpp
Labels: T:Internal

#3135 Prepare release 5.12.0
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3136 Typos in comments
  src/realm/impl/cont_transact_hist.hpp
Labels: T:Doc
