Repository realm/realm-core, pull requests merged in 2018-12, with the labels that each got.

#3180 Fix build logic in Jenkinsfile
  Jenkinsfile
Labels: T:Internal

#3183 Get_used_space fix
  CHANGELOG.md
  src/realm/group.cpp
Labels: T:Bug-Crash

#3184 Prepare version 5.12.4
  CHANGELOG.md
  dependencies.list
Labels: T:Bug

#3176 realm-trawler: Print out more Group info
  src/realm/realm_trawler.cpp
Labels: T:Internal

#3174 Fix warnings reported by GCC 8
  CHANGELOG.md
  src/realm/column_string_enum.cpp
  src/realm/query_engine.hpp
  src/realm/string_data.cpp
  src/realm/util/features.h
  src/realm/util/file.cpp
  src/realm/util/memory_stream.hpp
  test/test_thread.cpp
  test/test_upgrade_database.cpp
Labels: T:Internal

#3185 fix a race during initialization
  src/realm/util/file_mapper.cpp
  src/realm/util/file_mapper.hpp
Labels: T:Bug

#3188 Fsa/avoid early thread creation
  src/realm/util/file_mapper.cpp
Labels: T:Internal

#3189 Fix compilation without encryption
  src/realm/alloc_slab.cpp
  src/realm/util/file_mapper.hpp
Labels: T:Bug

#3190 Test without encryption in CI
  Jenkinsfile
Labels: T:Internal

#3191 Prepare version 5.12.5
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3194 Allow realm-core to be used from other cmake projects
  CMakeLists.txt
  src/realm/CMakeLists.txt
  tools/cmake/GetVersion.cmake
Labels: T:Internal

#3195 Fix problem with posix_fallocate on AWS Lambda
  CHANGELOG.md
  src/realm/group_writer.cpp
  src/realm/util/file.cpp
  src/realm/util/file.hpp
Labels: T:Bug-Crash

#3199 New tools
  CHANGELOG.md
  src/realm/CMakeLists.txt
  src/realm/exec/CMakeLists.txt
  src/realm/exec/config_tool.cpp
  src/realm/exec/importer.cpp
  src/realm/exec/importer.hpp
  src/realm/exec/importer_tool.cpp
  src/realm/exec/realm_browser.cpp
  src/realm/exec/realm_dump.c
  src/realm/exec/realm_trawler.cpp
  src/realm/exec/realmd.cpp
  src/realm/parser/CMakeLists.txt
  src/realm/schema_dumper.cpp
  tools/cross_compile.sh
Labels: T:Internal
