Repository realm/realm-core, pull requests merged in 2019-12, with the labels that each got.

#3502 Add ability to stream into an ObjectID
  CHANGELOG.md
  src/realm/object_id.cpp
  src/realm/object_id.hpp
  test/test_object_id.cpp
Labels: T-Enhancement

#3500 Core6: Use the right sized type for parsing column keys
  src/realm/impl/transact_log.hpp
Labels: T-Bug

#3505 Make TableView::get_parent() return a TableRef
  src/realm/table_view.cpp
  src/realm/table_view.hpp
  test/test_lang_bind_helper.cpp
  test/test_query.cpp
Labels: T-Internal

#3507 Better exception when upgrade needed in RO mode
  src/realm/db.cpp
  src/realm/db.hpp
  src/realm/exceptions.hpp
  src/realm/exec/realm2json.cpp
  src/realm/group.cpp
Labels: T-Internal

#3509 Rename ObjectId to GlobalKey
  src/realm/CMakeLists.txt
  src/realm/global_key.cpp
  src/realm/global_key.hpp
  src/realm/group.hpp
  src/realm/impl/transact_log.cpp
  src/realm/impl/transact_log.hpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/table.cpp
  src/realm/table.hpp
  test/CMakeLists.txt
  test/test_global_key.cpp
  test/test_object_id.cpp
Labels: T-Internal

#3517 Fix <filesystem> error on latest Visual Studio
  src/realm/util/file.hpp
  test/test_thread.cpp
Labels: T-Internal

#3514 Fix incorrect query results for NOT on a LinkList
  CHANGELOG.md
  src/realm/query_engine.cpp
  test/test_query.cpp
Labels: T-Bug

#3521 Prepare release 6.0.0-beta.1
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: T-Internal

#3528 Fix rebuilding pk columns with a null key
  CHANGELOG.md
  src/realm/obj.cpp
  test/test_group.cpp
Labels: T-Bug-Crash
