Repository realm/realm-core, pull requests merged in 2019-02, with the labels that each got.

#3233 Rename CircularBuffer to FixedSizeBuffer
  src/realm/CMakeLists.txt
  src/realm/metrics/metrics.hpp
  src/realm/util/fixed_size_buffer.hpp
  test/CMakeLists.txt
  test/test_util_fixed_size_buffer.cpp
  test/testsettings.hpp
Labels: T:Internal

#3237 fix for premature destruction of mutex
  CHANGELOG.md
  src/realm/util/file_mapper.cpp
  src/realm/util/file_mapper.hpp
Labels: T:Bug-Crash

#3239 Fix a race setting the encryption governor
  CHANGELOG.md
  src/realm/util/file_mapper.cpp
  src/realm/util/file_mapper.hpp
  test/test_all.cpp
  test/test_metrics.cpp
  test/test_transactions.cpp
Labels: T:Bug

#3236 Expose metrics query table name
  CHANGELOG.md
  src/realm/metrics/query_info.cpp
  src/realm/metrics/query_info.hpp
  test/test_metrics.cpp
Labels: T:Enhancement

#3238 prepare for 5.15.0
  CHANGELOG.md
  dependencies.list
  src/realm/metrics/query_info.cpp
  src/realm/metrics/query_info.hpp
  src/realm/util/file_mapper.cpp
  src/realm/util/file_mapper.hpp
  test/test_all.cpp
  test/test_metrics.cpp
  test/test_transactions.cpp
Labels: T:Internal

#3241 Use hardware optimized encryption functions
  CHANGELOG.md
  dependencies.list
  src/realm/util/aes_cryptor.hpp
  src/realm/util/encrypted_file_mapping.cpp
Labels: P:0 EXPEDITE, T:Enhancement

#3242 Update changelog
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3245 Add option to Group::write to strip history
  CHANGELOG.md
  src/realm/group.cpp
  src/realm/group.hpp
  src/realm/group_shared.cpp
  test/test_replication.cpp
Labels: T:Enhancement

#3247 Publish a TSAN build
  Jenkinsfile
  tools/cmake/SpecialtyBuilds.cmake
Labels: T:Internal

#3248 prepare for 5.16.0
  CHANGELOG.md
  dependencies.list
Labels: T:Internal
