Repository realm/realm-core, pull requests merged in 2019-08, with the labels that each got.

#3333 Clear m_primary_key_column when table acessor is refreshed
  CHANGELOG.md
  src/realm/table.cpp
Labels: T:Bug-Crash

#3328 Make FIFO files world readable on Android.
  CHANGELOG.md
  src/realm/CMakeLists.txt
  src/realm/util/fifo_helper.cpp
  src/realm/util/fifo_helper.hpp
  src/realm/util/interprocess_condvar.cpp
Labels: T:Bug-Crash

#3336 Create table top array with proper size
  src/realm/table.cpp
Labels: T:Internal

#3335 Update stored 'next sequence number' during migration
  CHANGELOG.md
  src/realm/table.cpp
Labels: T:Bug-Crash

#3337 Add type checks on list construction
  src/realm/list.cpp
  src/realm/list.hpp
Labels: T:Internal

#3338 Fix problem in Query::get_outside_versions()
  src/realm/query_engine.hpp
Labels: T:Internal

#3347 fix race in unittest Shared_WaitForChange which could cause it to hang
  CHANGELOG.md
  test/test_shared.cpp
Labels: T:Internal

#3348 Fix link to self
  CHANGELOG.md
  src/realm/cluster.cpp
  src/realm/exec/realm_trawler.cpp
  src/realm/table.cpp
  src/realm/table.hpp
  test/fuzz_group.cpp
  test/test_shared.cpp
Labels: T:Bug-Crash

#3349 Fix fastrand
  src/realm/utilities.cpp
  src/realm/utilities.hpp
  test/test_shared.cpp
Labels: T:Internal

#3351 Optimize timestamp queries: ==, !=, !NULL
  src/realm/array.hpp
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  test/benchmark-common-tasks/main.cpp
  test/test_query.cpp
Labels: T:Enhancement

#3354 Prepare version 5.23.2
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: T:Internal

#3356 Fix a query bug in average()/sum()
  CHANGELOG.md
  src/realm/array.hpp
  test/test_column.cpp
  test/test_query.cpp
Labels: T:Bug

#3357 fix for #3352
  CHANGELOG.md
  src/realm/util/file_mapper.cpp
Labels: T:Enhancement

#3361 No backtrace for query serialization errors
  CHANGELOG.md
  src/realm/exceptions.hpp
  src/realm/metrics/query_info.cpp
Labels: T:Internal

#3362 Add check for setting null values in non-nullable lists
  src/realm/column_type_traits.hpp
  src/realm/exceptions.cpp
  src/realm/exceptions.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/obj.cpp
  test/test_metrics.cpp
  test/test_table.cpp
Labels: T-Bug

#3364 Fix issue with import of detached linklist
  src/realm/db.cpp
  src/realm/db.hpp
  src/realm/list.hpp
  src/realm/obj.hpp
  test/test_lang_bind_helper.cpp
Labels: T-Bug-Crash

#3367 Add sort() and distinct() to List interface
  src/realm/list.cpp
  src/realm/list.hpp
  test/test_table.cpp
Labels: T-Feature

#3359 Changed metrics timers to report in nanoseconds
  CHANGELOG.md
  src/realm/metrics/metric_timer.cpp
  src/realm/metrics/metric_timer.hpp
  src/realm/metrics/query_info.cpp
  src/realm/metrics/query_info.hpp
  src/realm/metrics/transaction_info.cpp
  src/realm/metrics/transaction_info.hpp
  test/test_metrics.cpp
Labels: T-Internal

#3368 Ensure object is updated in ConstObj::get_backlink_count
  src/realm/obj.cpp
  test/test_links.cpp
Labels: T-Bug-Crash

#3371 Use correct define
  src/realm/util/fifo_helper.cpp
Labels: T-Bug

#3370 Optimize queries comparing a constant value over links
  CHANGELOG.md
  src/realm/data_type.hpp
  src/realm/query_expression.hpp
  test/benchmark-common-tasks/main.cpp
  test/test_query.cpp
Labels: T-Enhancement

#3372 Version bump to 5.23.3
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: T-Internal
