Repository realm/realm-core, pull requests merged in 2019-11, with the labels that each got.

#3437 Optimize Query::aggregate_internal a bit
  src/realm/query.cpp
  src/realm/query.hpp
Labels: T-Internal

#3452 Fix problem with leaf cache in BPlusTree
  src/realm/bplustree.cpp
  test/test_bplus_tree.cpp
Labels: T-Bug-Crash

#3443 Send cascade notifications in batches
  src/realm/array_backlink.cpp
  src/realm/cluster.cpp
  src/realm/cluster.hpp
  src/realm/cluster_tree.hpp
  src/realm/group.hpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/table.cpp
  src/realm/table.hpp
  test/test_group.cpp
  test/test_links.cpp
Labels: T-Enhancement

#3456 Add Lst::find_all()
  src/realm/bplustree.hpp
  src/realm/list.hpp
  test/test_links.cpp
Labels: T-Enhancement

#3457 Simplify cascading deletes a bit
  src/realm/cluster.cpp
  src/realm/obj.cpp
Labels: T-Enhancement

#3463 Enhanced freelist consistency check
  src/realm/group_writer.cpp
Labels: Pipeline-Review, T-Enhancement

#3451 Je/remove pk table
  src/realm/cluster.cpp
  src/realm/cluster_tree.hpp
  src/realm/group.cpp
  src/realm/group.hpp
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  src/realm/table.cpp
  src/realm/table.hpp
  test/test_group.cpp
  test/test_table.cpp
Labels: Pipeline-Review

#3461 Use a dispatch timer for the encrypted page reclaimer on Apple platforms
  CHANGELOG.md
  src/realm/util/file_mapper.cpp
Labels: Pipeline-Review, T-Enhancement

#3448 Make it a bit easier to build downstream projects with sanitizers enabled
  Dockerfile
  android.Dockerfile
  clang.Dockerfile
  generic.Dockerfile
  src/realm/CMakeLists.txt
  tools/build-cocoa.sh
  tools/cmake/SpecialtyBuilds.cmake
  tools/cmake/android.toolchain.cmake
  tools/cross_compile.sh
Labels: Pipeline-Review, T-Internal

#3460 Fix a race condition in subtable accessor deletion
  CHANGELOG.md
  src/realm/column_table.cpp
  src/realm/table.hpp
Labels: Pipeline-Review, T-Bug-Crash

#3464 Run longer running test on master and next-major
  Jenkinsfile
  src/realm/table.cpp
  test/test_file_locks.cpp
  test/test_index_string.cpp
  test/test_lang_bind_helper.cpp
  test/test_query.cpp
  test/test_shared.cpp
  test/test_thread.cpp
  test/test_transactions.cpp
Labels: Pipeline-Review

#3472 Fix upgrade of table with no columns
  CHANGELOG.md
  src/realm/table.cpp
  test/expect_test_upgrade_database_9_to_10.json
  test/test_upgrade_database.cpp
  test/test_upgrade_database_1000_9_to_10.realm
  test/test_upgrade_database_4_9_to_10.realm
Labels: T-Bug-Crash

#3473 Check object existence in Table::find_first<String>
  src/realm/table.cpp
  test/test_group.cpp
Labels: T-Bug

#3479 Delete views.cpp
  src/realm/views.cpp
Labels: T-Internal

#3462 Random access iterator
  CHANGELOG.md
  src/realm/cluster.cpp
  src/realm/cluster.hpp
  src/realm/cluster_tree.hpp
  src/realm/obj.hpp
  test/test_query.cpp
  test/test_table.cpp
Labels: Pipeline-Review, T-Enhancement

#3488 Fix potential error in File::get_file_pos
  src/realm/util/file.cpp
Labels: T-Internal

#3494 Fix assertion in SlabAlloc::allocate_block
  CHANGELOG.md
  src/realm/alloc_slab.cpp
  test/test_alloc.cpp
Labels: T-Bug

#3489 Use only one DB object in fuzz test
  src/realm/group.cpp
  test/fuzz_group.cpp
Labels: T-Internal

#3486 "Fix" sorting float columns containing NaN
  CHANGELOG.md
  src/realm/column.hpp
  test/test_table.cpp
Labels: T-Bug-Crash
