Repository realm/realm-core, pull requests merged in 2019-07, with the labels that each got.

#3311 Better performance of an IncludeDescriptor
  CHANGELOG.md
  src/realm/views.cpp
Labels: T:Bug

#3317 Fix metrics for unserializable queries throwing exceptions
  CHANGELOG.md
  src/realm/metrics/query_info.cpp
  test/test_metrics.cpp
Labels: T:Bug

#3319 Extra include descriptor testing
  test/test_parser.cpp
Labels: T:Test

#3320 Fix queries on indexed int columns which are not in table order
  CHANGELOG.md
  src/realm/query_engine.hpp
  test/test_query.cpp
Labels: T:Bug

#3321 Fix a memory leak when indexed int queries are run more than once
  CHANGELOG.md
  src/realm/query_engine.hpp
Labels: T:Bug

#3322 Version bump to 5.23.1
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: T:Internal

#3323 Release/5.23.1
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: T:Internal

#3325 Build releases for Apple platforms with Xcode 9.4
  CHANGELOG.md
  Jenkinsfile
Labels: T:Internal

#3324 Valgrind test
  Jenkinsfile
  src/realm/row.hpp
  test/test_destructor_thread_safety.cpp
  test/test_index_string.cpp
  test/test_lang_bind_helper.cpp
  valgrind.Dockerfile
Labels: T:Test

#3327 Avoid deleting and creating m_result array when re-running query
  src/realm/query_engine.hpp
  test/test_query.cpp
Labels: T:Internal

#3326 Make compile with GCC 8
  src/realm/list.cpp
  src/realm/table_view.cpp
Labels: T:Internal
