Repository realm/realm-core, pull requests merged in 2019-10, with the labels that each got.

#3407 Fsa/improve frozen api
  src/realm/db.hpp
  src/realm/group.cpp
  src/realm/group.hpp
  src/realm/obj.hpp
  src/realm/table.cpp
  src/realm/table.hpp
  src/realm/table_view.hpp
  test/test_lang_bind_helper.cpp
  test/test_transactions.cpp
Labels: T-Enhancement

#3420 Preserve the nullable attribute when migrating subtables to lists
  CMakeLists.txt
  src/realm/spec.cpp
Labels: T-Bug

#3417 Fix issue with DB outliving Replication object
  src/realm/db.cpp
  src/realm/replication.hpp
Labels: T-Bug-Crash

#3421 Improve performance of reading query results
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/obj.cpp
  src/realm/obj_list.cpp
  src/realm/obj_list.hpp
  src/realm/query.cpp
  src/realm/query.hpp
  src/realm/table_view.cpp
  src/realm/table_view.hpp
Labels: T-Enhancement

#3425 Introduce and use FunctionRef where it is safe
  src/realm/CMakeLists.txt
  src/realm/bplustree.cpp
  src/realm/bplustree.hpp
  src/realm/cluster.cpp
  src/realm/cluster_tree.hpp
  src/realm/column_binary.cpp
  src/realm/query.cpp
  src/realm/sort_descriptor.cpp
  src/realm/sort_descriptor.hpp
  src/realm/table.cpp
  src/realm/table.hpp
  src/realm/table_tpl.hpp
  src/realm/util/file.hpp
  src/realm/util/function_ref.hpp
  test/test_lang_bind_helper.cpp
  test/test_query_big.cpp
  test/test_table.cpp
Labels: T-Internal

#3428 Prepare release v6.0.0-alpha.22
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: T-Internal

#3429 Fix races in/around encryption layer
  CHANGELOG.md
  src/realm/alloc_slab.cpp
  src/realm/group_shared.cpp
  src/realm/group_writer.cpp
  src/realm/util/encrypted_file_mapping.cpp
  src/realm/util/encrypted_file_mapping.hpp
  src/realm/util/file.cpp
  src/realm/util/file.hpp
Labels: T-Bug-Crash

#3432 Use search index also when following links
  CHANGELOG.md
  src/realm/column_binary.hpp
  src/realm/column_timestamp.hpp
  src/realm/column_type_traits.hpp
  src/realm/mixed.hpp
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  src/realm/query_expression.cpp
  src/realm/query_expression.hpp
  src/realm/util/file.cpp
  test/test_query.cpp
Labels: T-Enhancement

#3438 Mixed array
  src/realm/CMakeLists.txt
  src/realm/array_mixed.cpp
  src/realm/array_mixed.hpp
  src/realm/array_string.hpp
  src/realm/mixed.hpp
  test/CMakeLists.txt
  test/test_array_mixed.cpp
  test/testsettings.hpp
Labels: T-Enhancement

#3424 Improve performance of looking up table entries by index
  CHANGELOG.md
  src/realm/array.hpp
  src/realm/cluster.cpp
  src/realm/cluster.hpp
  test/benchmark-common-tasks/main.cpp
Labels: T-Enhancement

#3431 Set the macOS deployment target properly
  CHANGELOG.md
  tools/cmake/macosx.toolchain.cmake
Labels: T-Bug

#3441 Implement ClusterTree::verify()
  src/realm/array.cpp
  src/realm/array.hpp
  src/realm/array_backlink.cpp
  src/realm/array_backlink.hpp
  src/realm/array_binary.cpp
  src/realm/array_binary.hpp
  src/realm/array_integer.cpp
  src/realm/array_integer.hpp
  src/realm/array_key.hpp
  src/realm/array_string.cpp
  src/realm/array_string.hpp
  src/realm/array_timestamp.cpp
  src/realm/array_timestamp.hpp
  src/realm/cluster.cpp
  src/realm/cluster.hpp
  src/realm/cluster_tree.hpp
  src/realm/table.hpp
Labels: T-Internal
