Repository realm/realm-core, pull requests merged in 2019-03, with the labels that each got.

#3250 Optimise queries search for a chain of OR strings
  CHANGELOG.md
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  test/benchmark-common-tasks/main.cpp
  test/test_parser.cpp
  test/test_query.cpp
Labels: T:Enhancement

#3100 Fix build on Visual Studio 2017 15.8
  CMakeLists.txt
Labels: T:Internal

#3251 Initialize replication in every transaction
  CHANGELOG.md
  src/realm/group.cpp
  src/realm/group_shared.cpp
  src/realm/group_shared.hpp
  src/realm/history.cpp
  src/realm/impl/cont_transact_hist.hpp
  src/realm/replication.cpp
  src/realm/replication.hpp
  test/test_lang_bind_helper.cpp
Labels: T:Internal

#3254 Fix format errors since v5.14.0
  CHANGELOG.md
  src/realm/group_shared_options.hpp
  src/realm/metrics/metrics.cpp
  src/realm/metrics/metrics.hpp
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  src/realm/util/file_mapper.cpp
  src/realm/util/file_mapper.hpp
  test/benchmark-common-tasks/main.cpp
  test/test_all.cpp
  test/test_metrics.cpp
  test/test_parser.cpp
Labels: T:Internal

#3255 Update CHANGELOG.md
  CHANGELOG.md
Labels: T:Internal

#3257 Prepare version 5.14.0-hotfix.1
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3256 Fix error in two column query
  CHANGELOG.md
  src/realm/array.hpp
  test/test_query.cpp
Labels: T:Bug-Crash

#3258 Prepare version 5.17.0
  CHANGELOG.md
  dependencies.list
Labels: T:Bug-Crash

#3261 Add support for backlink inclusions
  CHANGELOG.md
  src/realm/exceptions.hpp
  src/realm/handover_defs.hpp
  src/realm/parser/keypath_mapping.hpp
  src/realm/parser/parser.cpp
  src/realm/parser/parser.hpp
  src/realm/parser/query_builder.cpp
  src/realm/parser/query_builder.hpp
  src/realm/table_view.cpp
  src/realm/table_view.hpp
  src/realm/util/serializer.cpp
  src/realm/util/serializer.hpp
  src/realm/views.cpp
  src/realm/views.hpp
  test/test_parser.cpp
  test/test_query.cpp
Labels: T:Enhancement

#3263 Enhace LinksToNode so that it can check links to multiple targets
  CHANGELOG.md
  src/realm/query.cpp
  src/realm/query.hpp
  src/realm/query_engine.hpp
  test/test_link_query_view.cpp
Labels: T:Enhancement

#3264 Switch to building releases for Apple platforms with Xcode 9.2
  CHANGELOG.md
  Jenkinsfile
Labels: T:Internal

#3265 prepare 5.18.0
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3266 Fix error in Group::write
  CHANGELOG.md
  src/realm/group.cpp
  test/test_replication.cpp
Labels: T:Bug-Crash
