Repository realm/realm-core, pull requests merged in 2019-04, with the labels that each got.

#3272 Use index on int equal queries
  CHANGELOG.md
  src/realm/query_engine.hpp
  test/benchmark-common-tasks/main.cpp
  test/test_query.cpp
Labels: T:Enhancement

#3273 Bump version to 5.19.0
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3275 Release/5.19.0
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3276 Fix an incorrect debug mode assertion
  CHANGELOG.md
  src/realm/views.cpp
Labels: T:Bug

#3278 Fix unbound growth of freelist
  CHANGELOG.md
  src/realm/group_writer.cpp
  test/test_lang_bind_helper.cpp
Labels: T:Bug

#3279 Prepare v5.19.1
  CHANGELOG.md
  dependencies.list
Labels: T:Bug

#3277 Allow convertion of a Timestamp to a std::chrono::time_point
  CHANGELOG.md
  src/realm/timestamp.hpp
  test/test_column_timestamp.cpp
Labels: T:Internal

#3282 moved changelog entry to correct position
  CHANGELOG.md
Labels: T:Internal
