Repository realm/realm-core, pull requests merged in 2019-09, with the labels that each got.

#3374 Merge 5.23.3
  CHANGELOG.md
  src/realm/array.hpp
  src/realm/data_type.hpp
  src/realm/exceptions.hpp
  src/realm/metrics/metric_timer.cpp
  src/realm/metrics/metric_timer.hpp
  src/realm/metrics/query_info.cpp
  src/realm/metrics/query_info.hpp
  src/realm/metrics/transaction_info.cpp
  src/realm/metrics/transaction_info.hpp
  src/realm/query_expression.cpp
  src/realm/query_expression.hpp
  src/realm/util/fifo_helper.cpp
  src/realm/util/file_mapper.cpp
  test/benchmark-common-tasks/main.cpp
  test/test_metrics.cpp
  test/test_query.cpp
Labels: T-Internal

#3375 Threadsafe query
  src/realm/column_type_traits.hpp
  src/realm/parser/collection_operator_expression.hpp
  src/realm/parser/expression_container.cpp
  src/realm/parser/keypath_mapping.cpp
  src/realm/parser/keypath_mapping.hpp
  src/realm/parser/property_expression.cpp
  src/realm/parser/property_expression.hpp
  src/realm/parser/query_builder.cpp
  src/realm/parser/subquery_expression.cpp
  src/realm/parser/subquery_expression.hpp
  src/realm/parser/value_expression.cpp
  src/realm/parser/value_expression.hpp
  src/realm/query.cpp
  src/realm/query.hpp
  src/realm/query_expression.hpp
  src/realm/table.hpp
  test/test_metrics.cpp
  test/test_parser.cpp
Labels: T-Feature

#3380 Various small query optimizations
  src/realm/array_string.hpp
  src/realm/cluster.cpp
  src/realm/node.hpp
  src/realm/query_engine.hpp
Labels: T-Internal

#3382 Ability to sort as part of distinct on List
  src/realm/list.cpp
  src/realm/list.hpp
  test/test_table.cpp
Labels: T-Feature

#3384 Fsa/reduce mmap reservation
  CHANGELOG.md
  src/realm/alloc_slab.cpp
  src/realm/util/file.cpp
  src/realm/util/file.hpp
  src/realm/util/file_mapper.cpp
Labels: T-Enhancement

#3383 Update build scripts for Xcode 11
  CHANGELOG.md
  Jenkinsfile
  tools/build-cocoa.sh
  tools/cmake/Utilities.cmake
  tools/cmake/ios.toolchain.cmake
  tools/cmake/maccatalyst.toolchain.cmake
  tools/cmake/macosx.toolchain.cmake
  tools/cmake/tvos.toolchain.cmake
  tools/cmake/watchos.toolchain.cmake
  tools/cross_compile.sh
Labels: T-Internal

#3386 Fix incorrect results for long string or-equal queries
  CHANGELOG.md
  src/realm/array_string.hpp
  src/realm/array_string_long.hpp
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  test/test_query.cpp
Labels: T-Bug

#3389 Fix timestamp null description
  CHANGELOG.md
  src/realm/util/serializer.cpp
  test/test_parser.cpp
Labels: T-Bug

#3394 Include stacktrace for exception util::File::AccessError and it's derivatives
  CHANGELOG.md
  src/realm/util/file.hpp
Labels: T-Internal

#3391 VersionID comparison operators are now const qualified
  CHANGELOG.md
  src/realm/version_id.hpp
Labels: T-Internal

#3387 Fix issue with string index on 32 bit
  src/realm/index_string.cpp
  src/realm/query_engine.cpp
  src/realm/utilities.hpp
  test/test_index_string.cpp
Labels: T-Bug

#3399 Fix json serialisation of null values
  CHANGELOG.md
  src/realm/table.cpp
  test/expected_json_nulls.json
  test/test_json.cpp
Labels: T-Bug

#3398 Fix several warnings
  CHANGELOG.md
  src/realm/group.cpp
  src/realm/index_string.cpp
  src/realm/index_string.hpp
  src/realm/query_expression.hpp
Labels: T-Internal

#3400 Fix replication issues
  src/realm/list.cpp
  src/realm/obj.cpp
Labels: T-Internal

#3402 Fix query over LinkView involving string index
  CHANGELOG.md
  src/realm/impl/transact_log.hpp
  src/realm/obj.hpp
  test/test_query.cpp
Labels: T-Bug

#3406 Prepare version 6.0.0-alpha.19
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: T-Internal

#3401 we only need relaxed consistency for access to the table instance counter
  src/realm/alloc.hpp
  src/realm/table_ref.cpp
  src/realm/table_ref.hpp
Labels: T-Internal

#3409 Fix json serialization of list-of-primitives
  CHANGELOG.md
  src/realm/exec/CMakeLists.txt
  src/realm/exec/realm2json.cpp
  src/realm/table.cpp
  test/expect_json.json
  test/test_json.cpp
Labels: T-Bug
