Repository realm/realm-core, pull requests merged in 2019-01, with the labels that each got.

#3209 Fix potential problem in readdir() error handling
  CHANGELOG.md
  src/realm/util/file.cpp
Labels: T:Bug

#3200 Optimise find_first on small string arrays
  CHANGELOG.md
  src/realm/array_string.cpp
Labels: T:Internal

#3210 Prepare version 5.12.7
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3213 Allow calculation of sum of an empty array
  CHANGELOG.md
  src/realm/array.cpp
  test/test_array.cpp
Labels: T:Bug-Crash

#3214 Debug tools update
  src/realm/exec/realm_dump.c
  src/realm/exec/realm_trawler.cpp
Labels: T:Internal

#3215 Prepare version 5.13.0
  CHANGELOG.md
  dependencies.list
  test/bench/revs_to_benchmark.txt
  test/bench/util/build_benchmarks.sh
  test/bench/util/build_core.sh
Labels: T:Internal

#3211 added Durability::Unsafe
  CHANGELOG.md
  src/realm/alloc_slab.cpp
  src/realm/alloc_slab.hpp
  src/realm/group_shared.cpp
  src/realm/group_shared_options.hpp
  src/realm/group_writer.cpp
  src/realm/group_writer.hpp
Labels: T:Internal

#3219 Prepare release 5.14.0-ndk18.1
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3220 Prepare release 5.14.0-ndk18.2
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3225 Prepare version 5.14.0-ndk18.3
  CHANGELOG.md
  dependencies.list
Labels: T:Internal

#3226 SlabAlloc updates
  CHANGELOG.md
  src/realm/alloc_slab.cpp
  src/realm/alloc_slab.hpp
  src/realm/group.cpp
  src/realm/group_shared.cpp
  src/realm/group_shared.hpp
  test/test_shared.cpp
Labels: T:Enhancement

#3228 prepare 5.14.0
  CHANGELOG.md
  dependencies.list
Labels: T:Process

#3229 Release/5.14.0
  CHANGELOG.md
  dependencies.list
Labels: T:Process

#3224 Metrics improvements
  CHANGELOG.md
  src/realm/CMakeLists.txt
  src/realm/group_shared.cpp
  src/realm/group_shared_options.hpp
  src/realm/metrics/metrics.cpp
  src/realm/metrics/metrics.hpp
  src/realm/metrics/transaction_info.cpp
  src/realm/metrics/transaction_info.hpp
  src/realm/util/circular_buffer.hpp
  src/realm/util/file_mapper.cpp
  src/realm/util/file_mapper.hpp
  test/CMakeLists.txt
  test/test_metrics.cpp
  test/test_util_circular_buffer.cpp
  test/testsettings.hpp
Labels: T:Enhancement
