Repository realm/realm-core, pull requests merged in 2020-01, with the labels that each got.

#3533 Prepare release 6.0.0-beta.3
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: T-Internal

#3529 Update incoming links when table is rebuilt
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/query_expression.cpp
  src/realm/table_view.cpp
  test/test_group.cpp
Labels: T-Bug

#3538 Prepare release 5.23.8
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: T-Internal

#3545 Parser support for ObjectId
  src/realm/object_id.cpp
  src/realm/object_id.hpp
  src/realm/parser/parser.cpp
  src/realm/parser/parser.hpp
  src/realm/parser/parser_utils.cpp
  src/realm/parser/query_builder.cpp
  src/realm/parser/query_builder.hpp
  src/realm/parser/value_expression.cpp
  src/realm/query_expression.hpp
  src/realm/util/serializer.cpp
  src/realm/util/serializer.hpp
  test/test_parser.cpp
Labels: T-Enhancement

#3143 Add format check step in Jenkinsfile
  Jenkinsfile
  src/realm/alloc.cpp
Labels: T-Internal

#3565 Fix case insensitive search on string primary key column
  CHANGELOG.md
  src/realm/query_engine.hpp
  test/test_query2.cpp
Labels: T-Bug-Crash

#3560 Query parser support for Decimal128 type
  CHANGELOG.md
  src/realm/array_decimal128.hpp
  src/realm/bplustree.hpp
  src/realm/column_type_traits.hpp
  src/realm/decimal128.cpp
  src/realm/decimal128.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/parser/collection_operator_expression.hpp
  src/realm/parser/parser.cpp
  src/realm/parser/parser_utils.cpp
  src/realm/parser/parser_utils.hpp
  src/realm/parser/query_builder.cpp
  src/realm/parser/query_builder.hpp
  src/realm/parser/value_expression.cpp
  src/realm/query_expression.hpp
  src/realm/util/serializer.cpp
  src/realm/util/serializer.hpp
  test/test_decimal128.cpp
  test/test_parser.cpp
  test/test_table.cpp
Labels: T-Bug
