Repository realm/realm-core, pull requests merged in 2020-12, with the labels that each got.

#4158 Stop using protocol version ranges in WebSocket subprotocol header
  src/realm/sync/noinst/client_impl_base.cpp
Labels: T-Enhancement

#4161 Pull master -> develop
  CHANGELOG.md
  CMakeLists.txt
  Jenkinsfile
  src/realm/CMakeLists.txt
  src/realm/obj.cpp
  src/realm/object-store/CMakeLists.txt
  src/realm/object-store/sync/app_credentials.cpp
  src/realm/object-store/sync/app_credentials.hpp
  src/realm/object-store/sync/sync_user.cpp
  src/realm/object-store/util/bson/bson.cpp
  src/realm/object-store/util/bson/bson.hpp
  src/realm/object-store/util/tagged_string.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/table.cpp
  test/object-store/bson.cpp
  test/object-store/sync/app.cpp
  test/test_json.cpp
  test/test_query2.cpp
  tools/build-cocoa.sh
  tools/cmake/Utilities.cmake
  tools/cmake/ios.toolchain.cmake
  tools/cross_compile.sh
Labels: T-Internal

#4167 Je/rcore 368
  src/realm/impl/transact_log.hpp
  src/realm/object-store/impl/results_notifier.cpp
  src/realm/object-store/impl/transact_log_handler.cpp
  src/realm/object-store/object_changeset.cpp
  src/realm/object-store/object_changeset.hpp
  test/object-store/results.cpp
Labels: O-Community
