Repository realm/realm-core, pull requests merged in 2020-02, with the labels that each got.

#3580 Build tests for UWP
  CMakeLists.txt
  Jenkinsfile
  src/realm/util/file.hpp
  test/CMakeLists.txt
  test/Package.appxmanifest
  test/main.cpp
  test/test_all.cpp
  test/test_shared.cpp
  test/util/benchmark_results.cpp
  test/util/mem.cpp
  test/util/timer.cpp
Labels: T-Internal

#3588 Mark all move constructors/assignment operators as noexcept
  src/realm/alloc_slab.cpp
  src/realm/alloc_slab.hpp
  src/realm/bplustree.cpp
  src/realm/bplustree.hpp
  src/realm/keys.hpp
  src/realm/list.hpp
  src/realm/query.cpp
  src/realm/query.hpp
  src/realm/query_expression.hpp
  src/realm/util/file.hpp
  src/realm/util/optional.hpp
  src/realm/util/thread.hpp
Labels: T-Internal

#3596 Sort decimal128
  CHANGELOG.md
  src/realm/decimal128.cpp
  src/realm/decimal128.hpp
  src/realm/mixed.hpp
  src/realm/obj.cpp
  test/test_table.cpp
  test/test_table_view.cpp
Labels: T-Bug

#3601 Add missing symbol for Obj::set<Optional<ObjectId>>
  src/realm/list.cpp
  src/realm/obj.hpp
  test/test_table.cpp
Labels: T-Bug

#3547 Fix a crash on startup on macOS 10.10 and 10.11
  CHANGELOG.md
  src/realm/util/features.h
  src/realm/util/terminate.cpp
Labels: T-Bug-Crash
