Repository realm/realm-core, pull requests merged in 2021-01, with the labels that each got.

#4236 Catch failed bson parse
  CHANGELOG.md
  src/realm/object-store/sync/app.cpp
Labels: T-Bug-Crash

#4254 Copy TableView with different transaction version
  CHANGELOG.md
  src/realm/table_view.cpp
  test/test_table_view.cpp
Labels: T-Internal

#4263 Py/response refactoring
  CHANGELOG.md
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/app_utils.cpp
  src/realm/object-store/sync/generic_network_transport.hpp
  test/object-store/sync/app.cpp
Labels: T-Enhancement

#4343 Allow Mixed property to be indexed
  CHANGELOG.md
  src/realm/object-store/property.hpp
  test/object-store/object.cpp
Labels: T-Bug
