Repository realm/realm-core, pull requests merged in 2023-07, with the labels that each got.

#6764 C-API checks for Set in Mixed.
  src/realm/object-store/c_api/object.cpp
  test/object-store/c_api/c_api.cpp
Labels: cla: yes

#6765 Update BAAS version
  dependencies.list
  evergreen/config.yml
  test/object-store/sync/flx_sync.cpp
Labels: cla: yes, no-changelog

#6723 Improve client reset with additive schema changes
  CHANGELOG.md
  src/realm/object-store/sync/sync_manager.cpp
  src/realm/object-store/sync/sync_session.cpp
  src/realm/sync/client_base.hpp
  src/realm/sync/instruction_applier.hpp
  src/realm/sync/noinst/client_reset.cpp
  src/realm/sync/noinst/client_reset.hpp
  src/realm/sync/noinst/client_reset_operation.cpp
  src/realm/sync/noinst/client_reset_operation.hpp
  src/realm/sync/noinst/client_reset_recovery.cpp
  src/realm/sync/noinst/client_reset_recovery.hpp
  test/object-store/benchmarks/client_reset.cpp
  test/object-store/sync/flx_migration.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/sync/sync_test_utils.cpp
  test/object-store/sync/sync_test_utils.hpp
  test/object-store/util/test_file.cpp
  test/test_client_reset.cpp
Labels: cla: yes

#6768 Fix a use after free error in tests
  CHANGELOG.md
  src/realm/object-store/sync/async_open_task.cpp
  test/object-store/sync/flx_migration.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/sync/sync_test_utils.cpp
  test/object-store/sync/sync_test_utils.hpp
Labels: cla: yes, no-changelog

#6770 core v13.16.1
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: cla: yes

#6771 core v13.16.1
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: cla: yes

#6526 Unify error backoff handling in sync client
  CHANGELOG.md
  src/realm/sync/client.cpp
  src/realm/sync/client_base.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/sync/protocol.hpp
  src/realm/util/time.hpp
  test/CMakeLists.txt
  test/test_sync_error_backoff.cpp
Labels: cla: yes

#6774 Don't duplicate error messages for SyncError
  CHANGELOG.md
  src/realm/exceptions.cpp
  src/realm/exceptions.hpp
  test/object-store/sync/app.cpp
  test/test_util_file.cpp
  test/util/unit_test.cpp
Labels: cla: yes

#6769 [bindgen] Expose DeviceInfo::bundle_id
  bindgen/spec.yml
Labels: cla: yes

#6757 Run baas on remote ubuntu host for evergreen object-store-tests
  CHANGELOG.md
  evergreen/abspath.sh
  evergreen/build_libuv.sh
  evergreen/cmake_vars_utils.sh
  evergreen/config.yml
  evergreen/install_baas.sh
  evergreen/setup_baas_host.sh
  evergreen/setup_baas_host_local.sh
  evergreen/wait_for_baas.sh
  test/object-store/sync/client_reset.cpp
  test/object-store/sync/flx_sync.cpp
Labels: cla: yes

#6780 Add an option to pass a live Realm to the before-reset callback
  CHANGELOG.md
  src/realm.h
  src/realm/object-store/c_api/sync.cpp
  src/realm/object-store/sync/sync_session.cpp
  src/realm/sync/config.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/pending_bootstrap_store.hpp
  test/fuzz_tester.hpp
  test/object-store/sync/client_reset.cpp
  test/object-store/sync/flx_sync.cpp
  test/test_query2.cpp
Labels: cla: yes

#6782 A bit more testing in Many_ConcurrentReaders
  test/test_shared.cpp
Labels: cla: yes

#6781 print logs upon Many_ConcurrentReaders test failure
  test/test_shared.cpp
Labels: cla: yes, no-changelog

#6773 Deprecate `Object::obj()` for `Object::get_obj()`
  CHANGELOG.md
  src/realm/object-store/c_api/object.cpp
  src/realm/object-store/c_api/query.cpp
  src/realm/object-store/c_api/schema.cpp
  src/realm/object-store/c_api/types.hpp
  src/realm/object-store/collection.cpp
  src/realm/object-store/impl/object_accessor_impl.hpp
  src/realm/object-store/object.hpp
  src/realm/object-store/thread_safe_reference.cpp
  test/object-store/benchmarks/object.cpp
  test/object-store/c_api/c_api.cpp
  test/object-store/collection_fixtures.hpp
  test/object-store/dictionary.cpp
  test/object-store/frozen_objects.cpp
  test/object-store/geospatial.cpp
  test/object-store/list.cpp
  test/object-store/migrations.cpp
  test/object-store/object.cpp
  test/object-store/results.cpp
  test/object-store/sectioned_results.cpp
  test/object-store/sync/app.cpp
  test/object-store/sync/client_reset.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/thread_safe_reference.cpp
Labels: cla: yes

#6790 core v13.17.0
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: cla: yes

#6794 core v13.17.0
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: cla: yes

#6788 Update catch2 tags assigned to object store tests
  test/object-store/audit.cpp
  test/object-store/backup.cpp
  test/object-store/benchmarks/client_reset.cpp
  test/object-store/benchmarks/object.cpp
  test/object-store/benchmarks/results.cpp
  test/object-store/c_api/c_api.cpp
  test/object-store/collection_change_indices.cpp
  test/object-store/dictionary.cpp
  test/object-store/frozen_objects.cpp
  test/object-store/geospatial.cpp
  test/object-store/index_set.cpp
  test/object-store/list.cpp
  test/object-store/migrations.cpp
  test/object-store/realm.cpp
  test/object-store/results.cpp
  test/object-store/sectioned_results.cpp
  test/object-store/sync/app.cpp
  test/object-store/sync/client_reset.cpp
  test/object-store/sync/file.cpp
  test/object-store/sync/flx_migration.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/sync/metadata.cpp
  test/object-store/sync/migration_store_test.cpp
  test/object-store/sync/remote_mongo_tests.cpp
  test/object-store/sync/session/connection_change_notifications.cpp
  test/object-store/sync/session/progress_notifications.cpp
  test/object-store/sync/session/session.cpp
  test/object-store/sync/session/wait_for_completion.cpp
  test/object-store/sync/sync_manager.cpp
  test/object-store/sync/user.cpp
  test/object-store/util/baas_admin_api.cpp
Labels: cla: yes, no-changelog

#6796 Port upload/download completion API to Status
  CHANGELOG.md
  src/realm/object-store/sync/sync_session.cpp
  src/realm/sync/client.cpp
  src/realm/sync/client.hpp
  test/test_sync.cpp
Labels: cla: yes

#6802 Fix collection mismatch for `Set` in `Mixed`.
  src/realm/bplustree.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/set.hpp
  test/object-store/c_api/c_api.cpp
Labels: cla: yes

#6808 Delete some unused old code in SyncMetadataManager
  src/realm/object-store/sync/impl/sync_metadata.cpp
  src/realm/object-store/sync/impl/sync_metadata.hpp
Labels: cla: yes

#6814 Allow TypedLinks to be part of path to property in queries
  src/realm/collection.cpp
  src/realm/collection.hpp
  src/realm/query_expression.cpp
  src/realm/query_expression.hpp
  test/test_parser.cpp
  test/test_query2.cpp
Labels: cla: yes

#6803 Skip over objects already seen to speed up embedded object loop
  src/realm/object-store/schema.cpp
Labels: cla: yes

#6822 Remove comment since test is already enabled
  test/object-store/sync/flx_sync.cpp
Labels: no-changelog

#6784 Update error message when breaking changes are detected
  src/realm/object-store/object_store.cpp
  test/object-store/sync/flx_sync.cpp
Labels: cla: yes, no-changelog

#6823 Actually add full text indexes when processing schema changes that require them
  CHANGELOG.md
  src/realm/object-store/object_store.cpp
  test/object-store/sync/app.cpp
Labels: cla: yes

#6825 Add missing [baas] tag that is causing failing tests
  CHANGELOG.md
  test/object-store/sync/app.cpp
Labels: cla: yes, no-changelog

#6669 Sorting stage 2
  CHANGELOG.md
  src/realm/mixed.cpp
  src/realm/mixed.hpp
  src/realm/object-store/sectioned_results.cpp
  src/realm/parser/driver.cpp
  src/realm/parser/driver.hpp
  src/realm/parser/generated/query_bison.cpp
  src/realm/parser/generated/query_bison.hpp
  src/realm/parser/generated/query_flex.cpp
  src/realm/parser/query_bison.yy
  src/realm/parser/query_flex.ll
  src/realm/query_conditions.hpp
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  src/realm/util/serializer.cpp
  test/object-store/sectioned_results.cpp
  test/test_array_mixed.cpp
  test/test_parser.cpp
  test/test_query2.cpp
  test/test_set.cpp
Labels: cla: yes

#6826 Handle uploading logs in evg tasks on feature branches
  evergreen/config.yml
Labels: cla: yes, no-changelog

#6828 Sync progress for download messages from server state is updated wrongly
  CHANGELOG.md
  src/realm/sync/noinst/client_history_impl.cpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  test/test_sync.cpp
Labels: cla: yes

#6789 Consolidate object store sync util files into util/ directory
  CHANGELOG.md
  test/object-store/CMakeLists.txt
  test/object-store/audit.cpp
  test/object-store/benchmarks/CMakeLists.txt
  test/object-store/benchmarks/client_reset.cpp
  test/object-store/benchmarks/object.cpp
  test/object-store/benchmarks/results.cpp
  test/object-store/c_api/c_api.cpp
  test/object-store/geospatial.cpp
  test/object-store/migrations.cpp
  test/object-store/realm.cpp
  test/object-store/sync/app.cpp
  test/object-store/sync/client_reset.cpp
  test/object-store/sync/file.cpp
  test/object-store/sync/flx_migration.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/sync/metadata.cpp
  test/object-store/sync/migration_store_test.cpp
  test/object-store/sync/remote_mongo_tests.cpp
  test/object-store/sync/session/connection_change_notifications.cpp
  test/object-store/sync/session/progress_notifications.cpp
  test/object-store/sync/session/session.cpp
  test/object-store/sync/session/wait_for_completion.cpp
  test/object-store/sync/sync_manager.cpp
  test/object-store/sync/user.cpp
  test/object-store/util/sync/baas_admin_api.cpp
  test/object-store/util/sync/baas_admin_api.hpp
  test/object-store/util/sync/flx_sync_harness.hpp
  test/object-store/util/sync/session_util.hpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/object-store/util/sync/sync_test_utils.hpp
  test/object-store/util/test_file.cpp
  test/object-store/util/test_utils.cpp
Labels: cla: yes

#6829 Add new ErrorCodes for sync error handling
  src/realm/error_codes.cpp
  src/realm/error_codes.h
  src/realm/error_codes.hpp
Labels: cla: yes, no-changelog

#6824 Make SyncError/SessionErrorInfo Status-aware
  CHANGELOG.md
  src/realm/object-store/audit.mm
  src/realm/object-store/c_api/sync.cpp
  src/realm/object-store/sync/sync_session.cpp
  src/realm/sync/client.cpp
  src/realm/sync/client_base.hpp
  src/realm/sync/config.cpp
  src/realm/sync/config.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  test/object-store/audit.cpp
  test/object-store/sync/app.cpp
  test/object-store/sync/client_reset.cpp
  test/object-store/sync/flx_migration.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/sync/session/session.cpp
  test/object-store/sync/session/wait_for_completion.cpp
  test/object-store/util/test_file.cpp
  test/sync_fixtures.hpp
  test/test_client_reset.cpp
  test/test_sync.cpp
Labels: cla: yes

#6807 convert from streaming form *before* any changes to file size
  CHANGELOG.md
  src/realm/alloc_slab.cpp
  src/realm/alloc_slab.hpp
  src/realm/db.cpp
  src/realm/group.cpp
  src/realm/util/file_mapper.hpp
  test/test_alloc.cpp
Labels: cla: yes

#6783 Fix failed assertion for unknown app server errors
  CHANGELOG.md
  src/realm/error_codes.cpp
  src/realm/error_codes.h
  src/realm/error_codes.hpp
  src/realm/object-store/sync/app_utils.cpp
  src/realm/object-store/sync/generic_network_transport.cpp
  src/realm/object-store/sync/generic_network_transport.hpp
  test/object-store/sync/app.cpp
  test/object-store/util/sync/sync_test_utils.cpp
Labels: cla: yes

#6830 Add nightly test runs to evergreen config
  evergreen/config.yml
Labels: cla: yes, no-changelog
