Repository realm/realm-core, pull requests merged in 2023-12, with the labels that each got.

#6964 Js/device testing
  CHANGELOG.md
  Jenkinsfile
  test/CMakeLists.txt
  test/combined_tests.cpp
  test/object-store/CMakeLists.txt
  test/object-store/benchmarks/CMakeLists.txt
  test/object-store/c_api/c_api_file_tests.c
  test/object-store/main.cpp
  test/object-store/sync/session/session.cpp
  test/object-store/test_runner.cpp
  test/object-store/util/event_loop.cpp
  test/test_client_reset.cpp
  test/test_crypto.cpp
  test/test_sync.cpp
  test/test_sync_auth.cpp
  test/test_sync_history_migration.cpp
  test/test_util_network_ssl.cpp
  test/util/compare_groups.cpp
Labels: cla: yes

#7193 Update spec.yml to expose `Dictionary::add_key_based_notification_callback` correctly
  bindgen/spec.yml
Labels: T-Internal, no-changelog

#7199 Create GHA workflow to run unit tests
  .github/workflows/bindgen-unit-tests.yml
  bindgen/.mocharc.json
  bindgen/src/bound-model.ts
  package-lock.json
  package.json
Labels: T-Test, no-changelog

#7206 Disable failing ci builders
  evergreen/config.yml
  test/tsan.suppress
Labels: no-changelog

#7212 Update baas with fix for empty servers responses
  dependencies.list
  evergreen/config.yml
Labels: no-changelog

#7223 Enable the Parsley button in evergreen for uploaded file artifacts.
  evergreen/config.yml
Labels: no-changelog

#7224 Align run time for debug and simulator for slowests tests
  test/test_shared.cpp
  test/test_transform.cpp
Labels: no-changelog
