Repository realm/realm-core, pull requests merged in 2023-10, with the labels that each got.

#7005 Expose Table::get_primary_key_column
  bindgen/spec.yml
Labels: cla: yes

#7019 Remove redundant call to Query::find_all
  src/realm/object-store/impl/results_notifier.cpp
Labels: cla: yes

#6979 Don't report coverage for test files
  README.md
  evergreen/config.yml
Labels: cla: yes, no-changelog

#7003 Allow collections of non-embedded objects in asymmetric objects
  CHANGELOG.md
  src/realm/table.cpp
  test/object-store/audit.cpp
  test/object-store/realm.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/thread_safe_reference.cpp
  test/object-store/util/sync/flx_sync_harness.hpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/object-store/util/sync/sync_test_utils.hpp
  test/object-store/util/test_file.cpp
  test/object-store/util/test_file.hpp
Labels: cla: yes

#7008 New API and optimizations added to MutableSubscriptionSet
  CHANGELOG.md
  src/realm.h
  src/realm/object-store/c_api/sync.cpp
  src/realm/sync/subscriptions.cpp
  src/realm/sync/subscriptions.hpp
  test/object-store/c_api/c_api.cpp
  test/test_sync_subscriptions.cpp
Labels: cla: yes

#7022 Enable bundled OpenSSL certs for AOSP builds
  Android.bp
  CHANGELOG.md
Labels: cla: yes

#7025 Fix comment to better reflect async open logic
  src/realm/object-store/sync/async_open_task.cpp
Labels: cla: yes

#7028 Add Realm::is_empty
  bindgen/spec.yml
  bindgen/src/realm_helpers.h
  src/realm/object-store/shared_realm.cpp
  src/realm/object-store/shared_realm.hpp
  test/object-store/object.cpp
Labels: cla: yes

#7020 Filter TableView using custom function
  CHANGELOG.md
  src/realm/array.cpp
  src/realm/object-store/results.cpp
  src/realm/object-store/results.hpp
  src/realm/query.cpp
  src/realm/sort_descriptor.cpp
  src/realm/sort_descriptor.hpp
  src/realm/table.cpp
  src/realm/table.hpp
  src/realm/table_view.cpp
  src/realm/table_view.hpp
  test/benchmark-common-tasks/main.cpp
  test/object-store/results.cpp
  test/test_parser.cpp
  test/test_table_view.cpp
Labels: cla: yes

#6670 Sorting stage 3
  CHANGELOG.md
  src/realm/binary_data.hpp
  src/realm/collection.hpp
  src/realm/group.hpp
  src/realm/index_string.cpp
  src/realm/index_string.hpp
  src/realm/mixed.cpp
  src/realm/mixed.hpp
  src/realm/set.cpp
  src/realm/set.hpp
  src/realm/string_data.hpp
  src/realm/table.cpp
  src/realm/table.hpp
  src/realm/transaction.cpp
  src/realm/unicode.cpp
  src/realm/unicode.hpp
  test/test_array_mixed.cpp
  test/test_index_string.cpp
  test/test_set.cpp
  test/test_table_view.cpp
  test/test_upgrade_database.cpp
  test/test_upgrade_database_1000_23.realm
  test/test_upgrade_database_4_23.realm
  test/test_utf8.cpp
Labels: cla: yes

#6766 Client Reset for collections in mixed / nested collections
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/obj.cpp
  src/realm/object_converter.cpp
  src/realm/object_converter.hpp
  src/realm/sync/instruction_applier.cpp
  src/realm/sync/noinst/client_reset.cpp
  src/realm/sync/noinst/client_reset_recovery.cpp
  test/object-store/sync/client_reset.cpp
  test/test_list.cpp
Labels: cla: yes

#7004 Introduce logging categories
  src/realm.h
  src/realm/db.cpp
  src/realm/object-store/c_api/logging.cpp
  src/realm/query.cpp
  src/realm/replication.cpp
  src/realm/transaction.cpp
  src/realm/transaction.hpp
  src/realm/util/logger.cpp
  src/realm/util/logger.hpp
  src/realm/util/timestamp_logger.cpp
  src/realm/util/timestamp_logger.hpp
  test/object-store/c_api/c_api.cpp
  test/object-store/util/test_file.cpp
  test/object-store/util/test_file.hpp
  test/test_util_logger.cpp
  test/util/compare_groups.cpp
Labels: cla: yes

#7060 IQF compliant queries in migration tests
  test/object-store/sync/flx_migration.cpp
Labels: no-changelog

#6959 Fix blocked DB::open on multiprocess access on exFAT filesystem
  CHANGELOG.md
  src/realm/util/interprocess_mutex.hpp
  test/test_file.cpp
  test/test_shared.cpp
  test/util/test_path.cpp
  test/util/test_path.hpp
Labels: cla: yes

#7015 Added sync socket result enum for sync socket callback handlers in C API
  CHANGELOG.md
  src/realm.h
  src/realm/error_codes.h
  src/realm/object-store/c_api/socket_provider.cpp
  src/realm/object-store/c_api/types.hpp
  src/realm/sync/network/default_socket.cpp
  src/realm/sync/network/websocket.cpp
  src/realm/sync/network/websocket.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/server/server.cpp
  test/object-store/c_api/c_api.cpp
  test/test_util_websocket.cpp
Labels: cla: yes

#6911 Improve configurations for sanitized builds
  CHANGELOG.md
  Jenkinsfile
  bindgen/src/realm_helpers.h
  evergreen/config.yml
  src/external/s2/CMakeLists.txt
  src/realm/CMakeLists.txt
  src/realm/sync/noinst/client_history_impl.cpp
  src/realm/sync/transform.cpp
  src/realm/table.hpp
  src/realm/timestamp.hpp
  src/realm/util/logger.cpp
  src/realm/util/serializer.cpp
  src/realm/util/timestamp_logger.cpp
  test/CMakeLists.txt
  test/fuzz_tester.hpp
  test/object-store/audit.cpp
  test/object-store/migrations.cpp
  test/object-store/realm.cpp
  test/object-store/sync/flx_migration.cpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/test_json.cpp
  test/test_table.cpp
  test/util/unit_test.cpp
  test/util/unit_test.hpp
  tools/cmake/SpecialtyBuilds.cmake
Labels: cla: yes
