Repository realm/realm-core, pull requests merged in 2023-05, with the labels that each got.

#6550 Fix test build for geo feature, optimize copying
  src/realm/geospatial.cpp
  src/realm/geospatial.hpp
  src/realm/object-store/impl/object_accessor_impl.hpp
  src/realm/util/serializer.cpp
  test/object-store/geospatial.cpp
  test/test_parser.cpp
  test/test_query_geo.cpp
Labels: cla: yes, no-changelog

#6534 Print nested collections to Json
  src/realm/alloc.hpp
  src/realm/collection.cpp
  src/realm/collection.hpp
  src/realm/collection_list.cpp
  src/realm/collection_list.hpp
  src/realm/collection_parent.hpp
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/mixed.cpp
  src/realm/mixed.hpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/object-store/audit.mm
  src/realm/set.cpp
  src/realm/set.hpp
  src/realm/table.cpp
  test/expected_xjson_nested_dictionary.json
  test/expected_xjson_nested_dictionary1.json
  test/expected_xjson_nested_dictionary2.json
  test/expected_xjson_nested_dictionary3.json
  test/expected_xjson_nested_linklist1.json
  test/expected_xjson_nested_linklist2.json
  test/expected_xjson_nested_links.json
  test/test_json.cpp
Labels: cla: yes

#6529 Geospatial Polygons support holes
  src/realm/CMakeLists.txt
  src/realm/data_type.hpp
  src/realm/geospatial.cpp
  src/realm/geospatial.hpp
  src/realm/object-store/impl/object_accessor_impl.hpp
  src/realm/parser/driver.cpp
  src/realm/parser/driver.hpp
  src/realm/parser/generated/query_bison.cpp
  src/realm/parser/generated/query_bison.hpp
  src/realm/parser/query_bison.yy
  src/realm/util/config.h.in
  src/realm/util/serializer.cpp
  src/realm/util/serializer.hpp
  test/object-store/geospatial.cpp
  test/object-store/sync/flx_sync.cpp
  test/test_parser.cpp
  test/test_query_geo.cpp
Labels: cla: yes, no-changelog

#6560 Allow registering notifiers in write transactions prior to the first change
  CHANGELOG.md
  src/realm/object-store/shared_realm.cpp
  src/realm/transaction.cpp
  test/object-store/results.cpp
Labels: cla: yes

#6564 remove clang-format from Jenkins CI
  Jenkinsfile
Labels: cla: yes, no-changelog

#5943 Add basic coveralls code coverage tracking/reports to evergreen
  evergreen/config.yml
  tools/cmake/SpecialtyBuilds.cmake
Labels: cla: yes, no-changelog

#6394 Added parameter `service_name` to `realm_app_call_function`
  CHANGELOG.md
  src/realm.h
  src/realm/object-store/c_api/app.cpp
Labels: cla: yes

#6509 Ensure thread safety for memory mappings.
  CHANGELOG.md
  src/realm/alloc_slab.cpp
  src/realm/alloc_slab.hpp
Labels: cla: yes

#6517 Support excluding words in FTS
  CHANGELOG.md
  src/realm/index_string.cpp
  src/realm/index_string.hpp
  src/realm/tokenizer.cpp
  src/realm/tokenizer.hpp
  test/test_index_string.cpp
  test/test_query2.cpp
Labels: cla: yes

#6567 Reduce the memory footprint of an automatic reset
  CHANGELOG.md
  src/realm/sync/noinst/client_reset.cpp
Labels: cla: yes

#6480 Allow multiple app instances with the same ID but different base URLs
  CHANGELOG.md
  src/realm.h
  src/realm/object-store/c_api/app.cpp
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/app.hpp
  test/object-store/sync/app.cpp
Labels: cla: yes

#6563 Added CI tests for Clang 16/Ubuntu 22.04
  CHANGELOG.md
  evergreen/config.yml
Labels: cla: yes

#6574 core release 13.10.1
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: cla: yes

#6576 core release 13.10.1
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: cla: yes

#6575 Fix undefined behaviour issues
  src/realm/object-store/impl/deep_change_checker.hpp
  src/realm/object-store/shared_realm.cpp
Labels: no-changelog

#6573 Print websocket url as info debug
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/protocol.hpp
Labels: cla: yes, no-changelog

#6572 Update pinned server version and dump baas stacktrace on error
  dependencies.list
  evergreen/config.yml
Labels: cla: yes, no-changelog

#6472 Refactoring get_path()
  src/realm/collection_parent.hpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/sync/instruction_replication.cpp
  src/realm/sync/instruction_replication.hpp
  test/test_table.cpp
Labels: cla: yes

#6565 Store ref in ArrayMixed
  src/realm/array_mixed.cpp
  src/realm/array_mixed.hpp
  src/realm/collection.hpp
  src/realm/collection_list.cpp
  src/realm/collection_list.hpp
  src/realm/collection_parent.hpp
  src/realm/column_type.hpp
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/keys.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/mixed.hpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/object-store/dictionary.cpp
  src/realm/set.hpp
  test/test_list.cpp
Labels: cla: yes

#6580 Assorted binary size improvements
  Package.swift
  src/external/IntelRDFPMathLib20U2/CMakeLists.txt
  src/external/s2/CMakeLists.txt
  src/realm/alloc.hpp
  src/realm/collection.hpp
  src/realm/dictionary.hpp
  src/realm/geospatial.cpp
  src/realm/geospatial.hpp
  src/realm/list.hpp
  src/realm/obj.hpp
  src/realm/query_expression.cpp
  src/realm/query_expression.hpp
  src/realm/set.hpp
  src/realm/util/functional.hpp
  src/realm/util/serializer.cpp
  src/realm/util/serializer.hpp
Labels: cla: yes

#6263 Add Emscripten target
  CHANGELOG.md
  CMakeLists.txt
  Jenkinsfile
  Package.swift
  src/realm/CMakeLists.txt
  src/realm/object-store/CMakeLists.txt
  src/realm/object-store/c_api/CMakeLists.txt
  src/realm/object-store/impl/emscripten/external_commit_helper.cpp
  src/realm/object-store/impl/emscripten/external_commit_helper.hpp
  src/realm/object-store/impl/external_commit_helper.hpp
  src/realm/object-store/impl/realm_coordinator.cpp
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/impl/emscripten/network_transport.cpp
  src/realm/object-store/sync/impl/emscripten/network_transport.hpp
  src/realm/object-store/sync/impl/emscripten/socket_provider.cpp
  src/realm/object-store/sync/impl/emscripten/socket_provider.hpp
  src/realm/object-store/sync/impl/sync_client.hpp
  src/realm/object-store/sync/sync_manager.cpp
  src/realm/object-store/util/emscripten/scheduler.hpp
  src/realm/object-store/util/scheduler.cpp
  src/realm/sync/network/network_ssl.cpp
  src/realm/sync/noinst/server/CMakeLists.txt
  src/realm/sync/noinst/server/crypto_server_stub.cpp
  src/realm/sync/noinst/server/server_history.cpp
  src/realm/util/basic_system_errors.cpp
  src/realm/util/file.cpp
  src/realm/util/file.hpp
  src/realm/util/thread.cpp
  test/CMakeLists.txt
  test/object-store/CMakeLists.txt
  test/object-store/util/event_loop.cpp
Labels: cla: yes

#6583 Actually store collection type in Mixed
  src/realm/collection.cpp
  src/realm/collection.hpp
  src/realm/collection_list.cpp
  src/realm/collection_list.hpp
  src/realm/collection_parent.hpp
  src/realm/dictionary.hpp
  src/realm/list.hpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/object-store/dictionary.cpp
  src/realm/object-store/results.cpp
  src/realm/set.hpp
Labels: cla: yes

#6589 Fix clang-format printing on format failure
  evergreen/config.yml
Labels: cla: yes, no-changelog

#6584 Allow Dictionary to contain a collection
  src/realm/collection.hpp
  src/realm/collection_list.cpp
  src/realm/collection_list.hpp
  src/realm/collection_parent.cpp
  src/realm/collection_parent.hpp
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/list.hpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/table.hpp
  test/test_list.cpp
Labels: cla: yes

#6598 Apply clang-format only on staged changes
  tools/pre-commit
Labels: cla: yes, no-changelog

#6557 Make sync session multiplexing on-by-default
  CHANGELOG.md
  CMakeLists.txt
  evergreen/config.yml
  src/realm/object-store/CMakeLists.txt
  src/realm/object-store/sync/sync_manager.cpp
  src/realm/object-store/sync/sync_manager.hpp
  src/realm/object-store/sync/sync_session.cpp
  src/realm/object-store/sync/sync_session.hpp
  src/realm/sync/CMakeLists.txt
  src/realm/sync/client_base.hpp
  test/object-store/sync/session/session_util.hpp
  test/object-store/sync/sync_manager.cpp
  test/object-store/util/test_file.cpp
  test/object-store/util/test_file.hpp
Labels: cla: yes

#6599 Allow Lst<Mixed> to contain a collections
  src/realm/array_mixed.cpp
  src/realm/array_mixed.hpp
  src/realm/collection.hpp
  src/realm/collection_list.cpp
  src/realm/collection_parent.cpp
  src/realm/collection_parent.hpp
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/index_string.cpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/mixed.cpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/object-store/dictionary.cpp
  src/realm/object-store/impl/list_notifier.hpp
  src/realm/set.hpp
  src/realm/sync/instruction_applier.cpp
  src/realm/sync/instruction_applier.hpp
  src/realm/sync/noinst/client_reset_recovery.cpp
  test/test_list.cpp
Labels: cla: yes

#6604 `bindgen`: Refactored formatter to take callbacks
  bindgen/src/context.ts
  bindgen/src/formatter.ts
  bindgen/src/output-directory.ts
Labels: cla: yes

#6445 Fix crash on Results.freeze after owning collection removal
  CHANGELOG.md
  src/realm/object-store/results.cpp
  test/object-store/c_api/c_api.cpp
  test/object-store/frozen_objects.cpp
Labels: cla: yes

#6603 mark some tests nonconcurrent to reduce memory pressure on CI
  test/test_array.cpp
  test/test_table.cpp
Labels: cla: yes, no-changelog

#6602 Fix an error in client reset notifiers when using async open
  CHANGELOG.md
  src/realm/object-store/sync/sync_session.cpp
  test/object-store/sync/flx_migration.cpp
Labels: cla: yes

#6610 Bump protocol to v9 to indicate client has fix for client reset error during async open
  CHANGELOG.md
  src/realm/sync/protocol.hpp
  test/object-store/sync/flx_sync.cpp
Labels: cla: yes

#6616 fix missing includes of cstdint surfaced by gcc13
  CHANGELOG.md
  src/realm/error_codes.hpp
  src/realm/table_ref.hpp
  src/realm/util/to_string.hpp
Labels: cla: yes

#6617 Update changelog with PBS->FLX migration support update
  CHANGELOG.md
  src/realm/sync/protocol.hpp
Labels: cla: yes

#6608 Assembly in S2 math is disabled on watchos simulator builds
  src/external/s2/util/math/mathutil.h
Labels: cla: yes, no-changelog

#6613 Fix some issues in FTS
  CHANGELOG.md
  src/realm/index_string.cpp
  src/realm/tokenizer.cpp
  src/realm/tokenizer.hpp
  test/test_query2.cpp
Labels: cla: yes

#6619 bump version to 13.11.0
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: cla: yes

#6620 Release 13.11.0
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: cla: yes

#6612 Make core infer platform and cpu_arch, while bundle_id must be provided by SDK's
  CHANGELOG.md
  src/realm.h
  src/realm/object-store/c_api/app.cpp
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/app.hpp
  src/realm/util/features.h
  src/realm/util/platform_info.hpp
  test/object-store/c_api/c_api.cpp
  test/object-store/sync/app.cpp
  test/object-store/util/baas_admin_api.hpp
  test/object-store/util/test_file.cpp
Labels: cla: yes

#6477 Use consistent int rounding in S2 math
  src/external/s2/util/math/mathutil.cc
  src/external/s2/util/math/mathutil.h
  test/CMakeLists.txt
  test/test_query_geo.cpp
Labels: cla: yes, no-changelog

#6626 Update spec.yml for full-text search
  bindgen/spec.yml
Labels: cla: yes

#6632 fix entries that went to the wrong change version
  CHANGELOG.md
Labels: cla: yes

#6606 Improve SectionedResults performance
  CHANGELOG.md
  src/realm/mixed.cpp
  src/realm/mixed.hpp
  src/realm/object-store/results.cpp
  src/realm/object-store/results.hpp
  src/realm/object-store/sectioned_results.cpp
  src/realm/object-store/sectioned_results.hpp
  src/realm/object-store/util/apple/scheduler.hpp
  src/realm/object-store/util/scheduler.cpp
  src/realm/table_view.cpp
  src/realm/table_view.hpp
  test/object-store/benchmarks/results.cpp
  test/object-store/sectioned_results.cpp
  test/object-store/set.cpp
Labels: cla: yes

#6637 Fix some warnings
  src/external/IntelRDFPMathLib20U2/LIBRARY/src/bid128_string.c
  src/external/s2/base/casts.h
  src/external/s2/base/logging.h
  src/external/s2/base/macros.h
  test/test_query_geo.cpp
Labels: cla: yes, no-changelog

#6642 Fix importing Results with deleted collection
  src/realm/object-store/results.cpp
  test/object-store/frozen_objects.cpp
Labels: cla: yes

#6607 geospatial validation of polygons
  CHANGELOG.md
  src/external/s2/s2loop.cc
  src/external/s2/s2polygon.cc
  src/realm/geospatial.cpp
  src/realm/geospatial.hpp
  src/realm/parser/driver.cpp
  src/realm/query_expression.hpp
  test/test_parser.cpp
  test/test_query_geo.cpp
Labels: cla: yes, no-changelog

#6504 Optimize find_all_fulltext by using batch remove and replace
  test/benchmark-common-tasks/main.cpp
Labels: cla: yes

#6645 Geospatial feedback
  CHANGELOG.md
  src/realm/geospatial.cpp
  src/realm/geospatial.hpp
  src/realm/parser/driver.cpp
  src/realm/parser/driver.hpp
  src/realm/parser/generated/query_bison.cpp
  src/realm/parser/generated/query_bison.hpp
  src/realm/parser/generated/query_flex.cpp
  src/realm/parser/query_bison.yy
  src/realm/parser/query_flex.ll
  src/realm/query_expression.hpp
  test/object-store/sync/flx_sync.cpp
  test/test_parser.cpp
  test/test_query_geo.cpp
Labels: cla: yes

#6644 Filter out unresolved links in Dictionary::get_any()
  CHANGELOG.md
  src/realm/bplustree.hpp
  src/realm/dictionary.cpp
  src/realm/query_expression.cpp
  src/realm/query_expression.hpp
  src/realm/sort_descriptor.cpp
  src/realm/sort_descriptor.hpp
  test/test_unresolved_links.cpp
Labels: cla: yes

#6621 Geospatial basic queries benchmarks
  CHANGELOG.md
  src/realm/geospatial.cpp
  src/realm/geospatial.hpp
  src/realm/query_expression.hpp
  test/benchmark-common-tasks/CMakeLists.txt
  test/benchmark-common-tasks/main.cpp
Labels: cla: yes

#6650 Updated baas server tag for CI
  evergreen/config.yml
Labels: cla: yes, no-changelog

#6648 Set interface nested collections
  src/realm.h
  src/realm/collection.hpp
  src/realm/collection_parent.hpp
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/exceptions.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/mixed.cpp
  src/realm/obj.cpp
  src/realm/object-store/c_api/dictionary.cpp
  src/realm/object-store/c_api/list.cpp
  src/realm/object-store/collection.cpp
  src/realm/object-store/collection.hpp
  src/realm/set.hpp
  test/object-store/c_api/c_api.cpp
  test/object-store/nested_collections.cpp
Labels: cla: yes

#6636 Get path from collection objects
  src/realm/collection.hpp
  src/realm/collection_list.cpp
  src/realm/collection_list.hpp
  src/realm/collection_parent.cpp
  src/realm/collection_parent.hpp
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/sync/instruction_replication.cpp
  src/realm/sync/instruction_replication.hpp
  test/test_list.cpp
  test/test_table.cpp
Labels: cla: yes

#6631 Access token refresh for websockets was not updating the location metadata
  CHANGELOG.md
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/app.hpp
  src/realm/object-store/sync/sync_session.cpp
  test/object-store/CMakeLists.txt
  test/object-store/c_api/c_api.cpp
  test/object-store/sync/app.cpp
Labels: cla: yes

#6651 Maybe fix a race in a test
  test/object-store/sync/flx_sync.cpp
  test/object-store/sync/sync_test_utils.cpp
  test/object-store/sync/sync_test_utils.hpp
Labels: cla: yes, no-changelog

#6653 Use std::optional to store cached leaves in query nodes
  CHANGELOG.md
  src/realm/metrics/query_info.cpp
  src/realm/metrics/query_info.hpp
  src/realm/query.cpp
  src/realm/query.hpp
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  src/realm/query_expression.cpp
  src/realm/query_expression.hpp
  src/realm/table.cpp
  src/realm/utilities.hpp
  test/object-store/benchmarks/object.cpp
  test/object-store/benchmarks/results.cpp
  test/object-store/dictionary.cpp
  test/object-store/results.cpp
Labels: cla: yes

#6655 Add nested collection path in transaction log
  src/realm/collection.hpp
  src/realm/collection_list.cpp
  src/realm/collection_list.hpp
  src/realm/collection_parent.cpp
  src/realm/collection_parent.hpp
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/history.cpp
  src/realm/impl/transact_log.cpp
  src/realm/impl/transact_log.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/object-store/audit.mm
  src/realm/object-store/dictionary.cpp
  src/realm/object-store/impl/transact_log_handler.cpp
  src/realm/replication.cpp
  src/realm/replication.hpp
  src/realm/set.hpp
  src/realm/sync/instruction_replication.cpp
  src/realm/sync/instruction_replication.hpp
  test/test_lang_bind_helper.cpp
  test/test_list.cpp
  test/test_table.cpp
Labels: cla: yes

#6668 Sorting changes stage 1
  CHANGELOG.md
  src/realm/query_conditions.hpp
  src/realm/unicode.cpp
  src/realm/unicode.hpp
  src/realm/utilities.cpp
  test/test_table_view.cpp
  test/test_utf8.cpp
Labels: cla: yes

#6663 Allow geo coordinate numeric argument substitutions
  CHANGELOG.md
  src/realm/parser/driver.cpp
  src/realm/parser/driver.hpp
  src/realm/parser/generated/query_bison.cpp
  src/realm/parser/generated/query_bison.hpp
  src/realm/parser/query_bison.yy
  test/test_parser.cpp
Labels: cla: yes

#6667 Remove catch() clause to prevent truncating stack trace in AsyncOper::do_recycle_and_execute()
  CHANGELOG.md
  src/realm/sync/network/network.hpp
Labels: cla: yes

#6658 Replication of operations on nested collections
  src/realm/dictionary.cpp
  src/realm/impl/transact_log.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/sync/changeset.cpp
  src/realm/sync/changeset_encoder.cpp
  src/realm/sync/changeset_parser.cpp
  src/realm/sync/instruction_applier.cpp
  src/realm/sync/instruction_replication.cpp
  src/realm/sync/instruction_replication.hpp
  src/realm/sync/instructions.hpp
  src/realm/sync/transform.cpp
  test/test_sync.cpp
Labels: cla: yes

#6661 Fix an assertion failure if an async write callback ran during a write transaction
  CHANGELOG.md
  src/realm/object-store/shared_realm.cpp
  test/object-store/realm.cpp
  test/object-store/util/event_loop.cpp
  test/object-store/util/event_loop.hpp
Labels: cla: yes

#6677 core release 13.13.0
  CHANGELOG.md
  Package.swift
  dependencies.list
Labels: cla: yes

#6674 Allocate arguments for lists
  CHANGELOG.md
  src/realm/parser/driver.cpp
  src/realm/parser/driver.hpp
  test/object-store/c_api/c_api.cpp
Labels: cla: yes

#6672 Small documentation and code fixes
  src/realm/object-store/sync/sync_manager.cpp
  src/realm/object-store/sync/sync_manager.hpp
  src/realm/sync/instruction_applier.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/sync/noinst/client_reset.cpp
  src/realm/sync/noinst/migration_store.cpp
  src/realm/sync/noinst/migration_store.hpp
Labels: cla: yes, no-changelog

#6671 Fix crash when opening FLX realm after client reset failure
  CHANGELOG.md
  src/realm/object-store/sync/sync_session.cpp
  src/realm/sync/subscriptions.cpp
  src/realm/sync/subscriptions.hpp
  test/object-store/sync/flx_sync.cpp
Labels: cla: yes

#5311 Support sorting based on values from a dictionary
  CHANGELOG.md
  src/realm/object-store/results.cpp
  src/realm/parser/driver.cpp
  src/realm/parser/driver.hpp
  src/realm/sort_descriptor.cpp
  src/realm/sort_descriptor.hpp
  test/object-store/dictionary.cpp
  test/test_link_query_view.cpp
  test/test_parser.cpp
  test/test_table.cpp
  test/test_table_view.cpp
Labels: cla: yes

#6682 Filter out external sources from Eclipse
  .project
Labels: cla: yes

#6559 Use cross-compilers instead of CentOS image
  CHANGELOG.md
  CMakeLists.txt
  Jenkinsfile
  dependencies.list
  linux.Dockerfile
  packaging.Dockerfile
  tools/cmake/RealmConfig.cmake.in
  tools/cmake/aarch64-linux-gnu.toolchain.cmake
  tools/cmake/aarch64.toolchain.cmake
  tools/cmake/android-build-openssl.sh.in
  tools/cmake/armhf.toolchain.cmake
  tools/cmake/armv7-linux-gnueabihf.toolchain.cmake
  tools/cmake/linux.toolchain.base.cmake
  tools/cmake/run_ldconfig.sh
  tools/cmake/x86_64-linux-gnu.toolchain.cmake
Labels: cla: yes

#6685 Remap github URL to ssh to fix BAAS dependency using https://
  evergreen/install_baas.sh
Labels: cla: yes, no-changelog
