Repository realm/realm-core, pull requests merged in 2024-03, with the labels that each got.

#7398 Allow using aggregate operations on Mixed properties in queries
  CHANGELOG.md
  src/realm/parser/driver.cpp
  src/realm/query_expression.hpp
  test/test_parser.cpp
Labels: cla: yes

#7392 [bindgen] Enable support for collections in the `Mixed` data type
  bindgen/spec.yml
Labels: cla: yes

#7400 Avoid doing unneeded logger work in Replication
  CHANGELOG.md
  src/realm/replication.cpp
  src/realm/replication.hpp
Labels: cla: yes

#7406 Use the bfd linker in the armv7 toolchain
  CHANGELOG.md
  tools/cmake/armv7-linux-gnueabihf.toolchain.cmake
Labels: cla: yes

#7383 RCORE-1990 Add X86 Windows Release builder to evergreen
  evergreen/config.yml
Labels: cla: yes, no-changelog

#7407 Release 14.1.0
  CHANGELOG.md
  Package.swift
  dependencies.list
  tools/cmake/armv7-linux-gnueabihf.toolchain.cmake
Labels: cla: yes

#7403 Fix several crashes in the object store benchmarks
  CHANGELOG.md
  test/object-store/benchmarks/object.cpp
Labels: cla: yes

#7401 RCORE-1784 Add new index related benchmarks
  test/benchmark-common-tasks/main.cpp
Labels: cla: yes, no-changelog

#7409 Use updated curl on evergreen windows hosts
  evergreen/config.yml
Labels: cla: yes, no-changelog

#7411 Minimal changes to make CI pass if compression is always enabled. (Windows builds are failing because PR is missing master commits)
  src/realm/array_encode.cpp
  src/realm/group_writer.cpp
Labels: cla: yes

#7410 Delete leftover code for Set's order differing from Mixed
  CHANGELOG.md
  src/realm/bplustree.hpp
  src/realm/set.cpp
  src/realm/set.hpp
  test/util/compare_groups.cpp
Labels: cla: yes

#7415 Support regex for benchmarks selection
  test/benchmark-common-tasks/main.cpp
Labels: cla: yes, no-changelog

#7419 Add ability to get logging level via C API
  CHANGELOG.md
  src/realm.h
  src/realm/object-store/c_api/logging.cpp
  src/realm/util/logger.cpp
  src/realm/util/logger.hpp
  test/object-store/c_api/c_api.cpp
Labels: cla: yes

#7413 Add * wildcard matching for benchmark filters and fix a crash
  test/benchmark-common-tasks/main.cpp
Labels: cla: yes, no-changelog

#7394 RCORE-1928 Make dependencies.list a YAML file
  Android.bp
  CHANGELOG.md
  Jenkinsfile
  dependencies.list
  dependencies.yml
  evergreen/install_baas.sh
  evergreen/setup_baas_host_local.sh
  tools/cmake/GetVersion.cmake
  tools/generate-version-numbers-for-soong.sh
  tools/release-init.sh
  tools/release-tag.sh
Labels: cla: yes

#7421 Reduce boilerplate in collections in mixed unit test
  test/test_transform_collections_mixed.cpp
Labels: cla: yes, no-changelog

#7416 RCORE-1987 network::Service does not start waiting on timers if no other events are currently active
  src/realm/sync/network/network.hpp
Labels: no-changelog

#7404 Fix querying with a path into nested collections with wildcards
  CHANGELOG.md
  src/realm/collection.cpp
  src/realm/collection.hpp
  src/realm/obj.cpp
  src/realm/query_expression.cpp
  src/realm/query_expression.hpp
  test/test_parser.cpp
  test/test_query.cpp
Labels: cla: yes

#7427 Fix for 32 bit archs for encoded Arrays
  src/realm/array_direct.hpp
  src/realm/array_encode.hpp
  src/realm/array_flex.cpp
  src/realm/array_flex.hpp
  src/realm/array_packed.cpp
  src/realm/array_packed.hpp
  src/realm/node_header.hpp
Labels: cla: yes

#7424 Improve performance with very large numbers of notifiers
  CHANGELOG.md
  src/realm/group.hpp
  src/realm/object-store/impl/collection_notifier.cpp
  src/realm/object-store/impl/collection_notifier.hpp
  src/realm/object-store/impl/deep_change_checker.cpp
  test/object-store/benchmarks/object.cpp
Labels: cla: yes

#7429 🔄 Synced file(s) with realm/ci-actions
  .github/workflows/check-pr-title.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#7430 Remove flacky test
  test/test_list.cpp
Labels: cla: yes

#7431 enable dynamic choice of compression method
  src/realm/array_encode.cpp
  test/test_array_integer.cpp
Labels: cla: yes

#7432 moved typed_write/typed_print for bptree into class
  src/realm/bplustree.cpp
  src/realm/bplustree.hpp
  src/realm/cluster.cpp
Labels: cla: yes

#7433 Fix some warnings that Visual Studio keeps reporting
  src/realm/array.cpp
  src/realm/array_encode.hpp
  src/realm/node_header.hpp
Labels: cla: yes

#7436 Release core v14.2.0
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes

#7447 Fsa/unify subword search
  src/realm/array_direct.hpp
  src/realm/array_flex.cpp
  src/realm/array_flex.hpp
  src/realm/array_packed.cpp
  src/realm/array_packed.hpp
Labels: cla: yes

#7455 silence a warning from UBSAN (and also don't inline subword search, i…
  src/realm/array_direct.hpp
Labels: cla: yes

#7353 RCORE-1490 Sync collections in Mixed and nested collections
  CHANGELOG.md
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/obj.cpp
  src/realm/object-store/c_api/list.cpp
  src/realm/object_converter.cpp
  src/realm/sync/instruction_applier.cpp
  src/realm/sync/instruction_replication.cpp
  src/realm/sync/instruction_replication.hpp
  src/realm/sync/instructions.hpp
  src/realm/sync/transform.cpp
  test/CMakeLists.txt
  test/object-store/sync/client_reset.cpp
  test/test_all.cpp
  test/test_sync.cpp
  test/test_transform.cpp
  test/test_transform_collections_mixed.cpp
Labels: cla: yes

#7467 RCORE-2001 Make Scheduler's factory function a function pointer rather than a UniqueFunction
  CHANGELOG.md
  src/realm.h
  src/realm/object-store/c_api/scheduler.cpp
  src/realm/object-store/util/scheduler.cpp
  src/realm/object-store/util/scheduler.hpp
  test/object-store/benchmarks/main.cpp
  test/object-store/test_runner.cpp
Labels: cla: yes

#7423 RCORE-1928 Use baasaas for baas integration tests in CI
  CHANGELOG.md
  dependencies.yml
  evergreen/config.yml
  how-to-build.md
  test/object-store/CMakeLists.txt
  test/object-store/sync/app.cpp
  test/object-store/test_runner.cpp
  test/object-store/util/sync/baas_admin_api.cpp
  test/object-store/util/sync/baas_admin_api.hpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/object-store/util/sync/sync_test_utils.hpp
  test/object-store/util/test_file.cpp
  test/object-store/util/test_file.hpp
Labels: cla: yes

#7402 Make Obj trivial and add a separate ObjCollectionParent type
  CHANGELOG.md
  src/realm/collection.cpp
  src/realm/collection.hpp
  src/realm/collection_parent.cpp
  src/realm/collection_parent.hpp
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/object-store/collection_notifications.hpp
  src/realm/object-store/impl/collection_notifier.cpp
  src/realm/object-store/impl/collection_notifier.hpp
  src/realm/object-store/impl/list_notifier.cpp
  src/realm/object-store/impl/list_notifier.hpp
  src/realm/object-store/impl/object_notifier.cpp
  src/realm/object-store/impl/results_notifier.cpp
  src/realm/object-store/impl/transact_log_handler.cpp
  src/realm/path.hpp
  src/realm/replication.cpp
  src/realm/set.cpp
  src/realm/set.hpp
  src/realm/transaction.cpp
  src/realm/util/logger.hpp
  test/object-store/audit.cpp
  test/object-store/benchmarks/client_reset.cpp
  test/object-store/dictionary.cpp
  test/object-store/nested_collections.cpp
  test/object-store/object.cpp
  test/object-store/primitive_list.cpp
  test/test_client_reset.cpp
  test/test_list.cpp
  test/test_parser.cpp
Labels: cla: yes, no-jira-ticket

#7418 Improve performance of aggregate operations on empty dictionaries
  CHANGELOG.md
  src/realm/collection.hpp
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/object-store/results.cpp
  src/realm/table.cpp
  src/realm/table.hpp
Labels: cla: yes

#7441 RCORE-2007 Added Resumption delay configuration to SyncClientTimeouts
  CHANGELOG.md
  bindgen/spec.yml
  src/realm.h
  src/realm/object-store/c_api/sync.cpp
  src/realm/object-store/sync/impl/sync_client.hpp
  src/realm/object-store/sync/sync_manager.cpp
  src/realm/object-store/sync/sync_manager.hpp
  src/realm/sync/client.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  test/object-store/c_api/c_api.cpp
Labels: cla: yes

#7479 changed heuristics governing integer leaf compression
  src/realm/array_encode.cpp
  test/test_array_integer.cpp
Labels: cla: yes

#7439 Improve queries for encoded arrays.
  src/realm/array.cpp
  src/realm/array.hpp
  src/realm/array_direct.hpp
  src/realm/array_encode.cpp
  src/realm/array_encode.hpp
  src/realm/array_flex.cpp
  src/realm/array_flex.hpp
  src/realm/array_integer.cpp
  src/realm/array_integer_tpl.hpp
  src/realm/array_packed.cpp
  src/realm/array_packed.hpp
  src/realm/array_unsigned.cpp
  src/realm/parser/generated/query_flex.cpp
  src/realm/parser/generated/query_flex.hpp
  test/test_array_integer.cpp
Labels: cla: yes

#7483 Fix getter lower upper bound
  src/realm/array_direct.hpp
Labels: cla: yes

#7482 core v14.3.0
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes

#7485 Release core v14.3.0
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes

#7470 Update the parent's content version when bumping it in a nested collection
  CHANGELOG.md
  src/realm/collection.hpp
  src/realm/collection_parent.hpp
  src/realm/dictionary.hpp
  src/realm/list.hpp
  src/realm/obj.hpp
  test/test_list.cpp
Labels: cla: yes, no-jira-ticket

#7492 Set the minimum buffer size in Group::write() to be equal to the page size
  CHANGELOG.md
  src/realm/group.cpp
Labels: cla: yes, no-jira-ticket

#7486 RCORE-2028 fix depth for nested collections set to 4 in debug mode
  CHANGELOG.md
  src/realm/collection_parent.hpp
Labels: cla: yes

#7489 RCORE-2005: Include nested path in 'OutOfBounds' error message
  CHANGELOG.md
  src/realm/collection.cpp
  src/realm/collection.hpp
  test/test_list.cpp
Labels: cla: yes

#7471 Derive correct ubuntu version on linuxmint
  evergreen/install_baas.sh
Labels: cla: yes

#7493 Disable timestamps for compressed arrays.
  src/realm/cluster.cpp
Labels: cla: yes

#7499 RCORE-2008 Bump baas version
  dependencies.yml
Labels: cla: yes, no-changelog

#7496 Heuristics parallel subscan flex
  src/realm/array_direct.hpp
  src/realm/array_encode.cpp
  src/realm/array_flex.cpp
  src/realm/array_flex.hpp
  src/realm/array_packed.cpp
  src/realm/array_packed.hpp
Labels: cla: yes

#7469 RCORE-1982 Opening realm with cached user while offline results in fatal error and session does not retry connection
  CHANGELOG.md
  src/realm.h
  src/realm/object-store/c_api/app.cpp
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/app.hpp
  src/realm/object-store/sync/sync_manager.cpp
  src/realm/object-store/sync/sync_manager.hpp
  src/realm/object-store/sync/sync_session.cpp
  src/realm/object-store/sync/sync_session.hpp
  src/realm/sync/client.cpp
  src/realm/sync/client.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  test/object-store/c_api/c_api.cpp
  test/object-store/sync/app.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/util/sync/baas_admin_api.hpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/object-store/util/sync/sync_test_utils.hpp
  test/object-store/util/test_file.cpp
  test/object-store/util/test_file.hpp
  test/object-store/util/unit_test_transport.hpp
Labels: cla: yes

#7481 🔄 Synced file(s) with realm/ci-actions
  .github/workflows/lock-threads.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#7502 Disallow Set inside ArrayMixed
  CHANGELOG.md
  src/realm/array_mixed.cpp
Labels: cla: yes

#7500 RCORE-2035 threadsafe realm for init subscription callback
  CHANGELOG.md
  src/realm.h
  src/realm/object-store/c_api/sync.cpp
  test/object-store/c_api/c_api.cpp
Labels: cla: yes

#7507 RCORE-2037: [bindgen] smaller fixes after 14.4.0
  bindgen/spec.yml
Labels: cla: yes

#7511 prepare v14.4.1
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes

#7513 Merge Release/14.4.1
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes

#7124 RCORE-2011: New parameter 'progress_estimate' for sync progress notification
  CHANGELOG.md
  bindgen/spec.yml
  src/realm.h
  src/realm/object-store/c_api/sync.cpp
  src/realm/object-store/sync/async_open_task.cpp
  src/realm/object-store/sync/async_open_task.hpp
  src/realm/object-store/sync/sync_session.cpp
  src/realm/object-store/sync/sync_session.hpp
  src/realm/sync/client.cpp
  src/realm/sync/client.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/sync/noinst/protocol_codec.hpp
  src/realm/sync/protocol.hpp
  test/object-store/realm.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/sync/session/progress_notifications.cpp
  test/object-store/util/test_file.hpp
  test/test_sync.cpp
  test/tsan.suppress
Labels: cla: yes

#7501 Compression for leaf Mixed arrays of integers and collection in mixed.
  src/realm/bplustree.cpp
  src/realm/bplustree.hpp
  src/realm/cluster.cpp
  test/test_list.cpp
Labels: cla: yes

#7516 Demote some assertions inside commit hot path to trigger only in debug mode
  src/realm/array.cpp
  src/realm/array_direct.hpp
  src/realm/array_flex.hpp
  src/realm/array_packed.hpp
  src/realm/bplustree.cpp
  src/realm/cluster.cpp
  src/realm/node_header.hpp
Labels: cla: yes

#7508 RCORE-1984 Upgrade libuv to v1.48.0 for object-store tests
  CHANGELOG.md
  test/object-store/CMakeLists.txt
Labels: cla: yes

#7515 Made `set_default_logger` nullable in `spec.yml`
  CHANGELOG.md
  bindgen/spec.yml
Labels: cla: yes, no-jira-ticket

#7487 RCORE-2006 Reuse realm file for sync schema migrations
  src/realm/group.cpp
  src/realm/group.hpp
  src/realm/object-store/object_store.cpp
  src/realm/object-store/object_store.hpp
  src/realm/object-store/schema.hpp
  src/realm/object-store/shared_realm.cpp
  src/realm/object-store/sync/async_open_task.cpp
  src/realm/object-store/sync/sync_session.cpp
  src/realm/object-store/sync/sync_session.hpp
  src/realm/sync/noinst/client_history_impl.cpp
  src/realm/sync/noinst/client_history_impl.hpp
  src/realm/sync/noinst/client_reset.cpp
  src/realm/sync/noinst/client_reset.hpp
  src/realm/sync/noinst/pending_bootstrap_store.cpp
  src/realm/sync/noinst/pending_bootstrap_store.hpp
  src/realm/sync/noinst/sync_schema_migration.cpp
  src/realm/sync/noinst/sync_schema_migration.hpp
  src/realm/sync/subscriptions.cpp
  src/realm/sync/subscriptions.hpp
  test/object-store/migrations.cpp
  test/object-store/sync/client_reset.cpp
  test/object-store/sync/flx_schema_migration.cpp
  test/test_sync_subscriptions.cpp
Labels: cla: yes, no-changelog

#7524 Add new builder with compression always enabled for verifying correctness
  CMakeLists.txt
  evergreen/config.yml
  src/realm/array_encode.cpp
  src/realm/array_encode.hpp
  src/realm/util/config.h.in
  test/test_array_integer.cpp
Labels: cla: yes

#7517 Update 'release-init.sh' script to update git submodules prior to starting the release process
  tools/release-init.sh
Labels: cla: yes, no-changelog, no-jira-ticket

#7522 Move optimisation code for Array into separate cpp file and remove ArrayEncode::sum
  src/realm/CMakeLists.txt
  src/realm/array.cpp
  src/realm/array_aggregate_optimizations.cpp
  src/realm/array_encode.cpp
  src/realm/array_encode.hpp
  src/realm/array_flex.cpp
  src/realm/array_flex.hpp
  src/realm/array_packed.cpp
  src/realm/array_packed.hpp
Labels: cla: yes

#7448 RCOCOA-2301 Remove the emulated InterprocessMutex File cache
  CHANGELOG.md
  src/realm/util/interprocess_mutex.cpp
  src/realm/util/interprocess_mutex.hpp
Labels: cla: yes
