Repository realm/realm-core, pull requests merged in 2024-07, with the labels that each got.

#7856 RCORE-2188 fix gcc warnings and add a ubuntu 2404 GCC runner
  evergreen/config.yml
  src/external/s2/s2polygonbuilder.cc
  src/realm/sync/noinst/client_reset_recovery.cpp
  src/realm/util/cli_args.cpp
Labels: cla: yes, no-changelog

#7796 RCORE-2160 Make upload completion reporting multiprocess-compatible
  CHANGELOG.md
  src/realm/chunked_binary.cpp
  src/realm/chunked_binary.hpp
  src/realm/sync/client.cpp
  src/realm/sync/noinst/client_history_impl.cpp
  src/realm/sync/noinst/client_history_impl.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/test_client_reset.cpp
Labels: cla: yes

#7831 RCORE-2174 Bootstrap store is not being reset if initial subscription bootstrap is interrupted by role change
  CHANGELOG.md
  src/realm/sync/client.cpp
  src/realm/sync/noinst/client_impl_base.cpp
  test/object-store/sync/flx_role_change.cpp
Labels: cla: yes

#7576 RCORE-1900 Make "next launch" metadata actions multiprocess-safe
  CHANGELOG.md
  src/realm/db.cpp
  src/realm/db.hpp
  src/realm/object-store/impl/realm_coordinator.hpp
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/async_open_task.cpp
  src/realm/object-store/sync/impl/app_metadata.cpp
  src/realm/object-store/sync/impl/app_metadata.hpp
  test/object-store/c_api/c_api.cpp
  test/object-store/realm.cpp
  test/object-store/results.cpp
  test/object-store/sync/client_reset.cpp
  test/object-store/sync/flx_schema_migration.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/sync/metadata.cpp
  test/object-store/test_runner.cpp
  test/object-store/thread_safe_reference.cpp
  test/test_sync.cpp
Labels: cla: yes

#7751 [RCORE-2146] CAPI Remove `is_fatal` flag flip
  CHANGELOG.md
  src/realm/object-store/c_api/sync.cpp
Labels: cla: yes

#7850 RCORE-2185 Sync client should steal file ident of fresh realm when performing client reset
  CHANGELOG.md
  src/realm/object-store/sync/sync_session.cpp
  src/realm/sync/client.cpp
  src/realm/sync/client.hpp
  src/realm/sync/config.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/sync/noinst/client_reset.cpp
  src/realm/sync/noinst/client_reset.hpp
  src/realm/sync/noinst/client_reset_operation.cpp
  src/realm/sync/noinst/client_reset_operation.hpp
  test/object-store/sync/flx_migration.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/test_client_reset.cpp
Labels: cla: yes

#7675 RCORE-1973 Add role/permissions tests for new bootstrap feature
  CHANGELOG.md
  dependencies.yml
  src/realm/sync/client.cpp
  src/realm/sync/noinst/client_impl_base.cpp
  test/object-store/CMakeLists.txt
  test/object-store/sync/flx_role_change.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/util/sync/baas_admin_api.cpp
Labels: cla: yes

#7841 Building for Windows using C++20
  CHANGELOG.md
  CMakeLists.txt
  evergreen/config.yml
  src/external/bson/bson-decimal128.c
  src/external/bson/bson-iter.c
  src/realm/util/file.cpp
  test/benchmark-common-tasks/main.cpp
  test/util/test_path.cpp
Labels: cla: yes, no-jira-ticket

#7864 [C-API] Add relaxed schema configuration option
  src/realm.h
  src/realm/object-store/c_api/config.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7863 [bindgen] Add to configuration
  bindgen/spec.yml
Labels: no-changelog, no-jira-ticket

#7812 RCORE-2170 String compression tests
  evergreen/config.yml
  src/realm/string_interner.cpp
  test/CMakeLists.txt
  test/test_group.cpp
  test/test_string_compression.cpp
Labels: cla: yes, no-changelog

#7868 Remove `typed_print`
  evergreen/config.yml
  src/realm/array.cpp
  src/realm/array.hpp
  src/realm/bplustree.cpp
  src/realm/bplustree.hpp
  src/realm/cluster.cpp
  src/realm/cluster.hpp
  src/realm/cluster_tree.cpp
  src/realm/cluster_tree.hpp
  src/realm/group.cpp
  src/realm/group.hpp
  src/realm/node.hpp
  src/realm/spec.hpp
  src/realm/table.cpp
  src/realm/table.hpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7875 Bump baas
  dependencies.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#7858 Remove enum string feature
  CHANGELOG.md
  src/realm/array_string.cpp
  src/realm/array_string.hpp
  src/realm/cluster.cpp
  src/realm/cluster.hpp
  src/realm/cluster_tree.cpp
  src/realm/cluster_tree.hpp
  src/realm/exec/CMakeLists.txt
  src/realm/exec/realm_enumerate.cpp
  src/realm/node.hpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  src/realm/spec.cpp
  src/realm/spec.hpp
  src/realm/table.cpp
  src/realm/table.hpp
  test/expect_json.json
  test/expect_xjson.json
  test/expect_xjson_plus.json
  test/fuzz_group.cpp
  test/realm-fuzzer/fuzz_engine.cpp
  test/realm-fuzzer/fuzz_object.cpp
  test/realm-fuzzer/fuzz_object.hpp
  test/realm-fuzzer/util.hpp
  test/test_group.cpp
  test/test_index_string.cpp
  test/test_json.cpp
  test/test_lang_bind_helper.cpp
  test/test_links.cpp
  test/test_query.cpp
  test/test_query2.cpp
  test/test_shared.cpp
  test/test_table.cpp
  test/test_table_view.cpp
  test/test_transactions.cpp
Labels: cla: yes

#7820 RCORE-2064 String EQ/NEQ optimisations for compressed strings
  src/realm/array_string.cpp
  src/realm/array_string.hpp
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  src/realm/table.cpp
  test/test_query.cpp
Labels: cla: yes, no-changelog

#7871 Fix data races in the connection state changes tests
  CHANGELOG.md
  test/object-store/sync/session/connection_change_notifications.cpp
Labels: cla: yes, no-jira-ticket

#7877 RJS-2858: Allow both internal and public name in realm::Results::{sort, distinct}
  CHANGELOG.md
  src/realm/object-store/results.cpp
  test/object-store/results.cpp
Labels: cla: yes

#7519 Initial support for additional properties
  bindgen/spec.yml
  src/realm.h
  src/realm/db.cpp
  src/realm/db.hpp
  src/realm/db_options.hpp
  src/realm/group.cpp
  src/realm/group.hpp
  src/realm/impl/array_writer.hpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/object-store/c_api/config.cpp
  src/realm/object-store/c_api/object.cpp
  src/realm/object-store/impl/realm_coordinator.cpp
  src/realm/object-store/object.hpp
  src/realm/object-store/object_accessor.hpp
  src/realm/object-store/shared_realm.hpp
  src/realm/sync/instruction_applier.cpp
  src/realm/sync/instruction_replication.cpp
  src/realm/sync/instruction_replication.hpp
  src/realm/sync/noinst/server/server_file_access_cache.hpp
  src/realm/table.cpp
  src/realm/table.hpp
  src/realm/transaction.cpp
  test/object-store/c_api/c_api.cpp
  test/test_sync.cpp
Labels: cla: yes

#7879 Update return type of `LogCategory::get_category_names()` from `std::vector<const char*>` to `std::vector<std::string_view>`
  CHANGELOG.md
  src/realm/object-store/c_api/logging.cpp
  src/realm/util/logger.cpp
  src/realm/util/logger.hpp
Labels: cla: yes, no-jira-ticket

#7882 RCORE-2196 Use the Windows trusted root certificates for TLS
  CHANGELOG.md
  src/realm/sync/CMakeLists.txt
  src/realm/sync/network/network_ssl.cpp
  src/realm/sync/network/network_ssl.hpp
  test/test_util_network_ssl.cpp
Labels: cla: yes

#7870 RCORE-2192 RCORE-2193 Fix FLX download progress reporting
  CHANGELOG.md
  src/realm/object-store/sync/async_open_task.cpp
  src/realm/object-store/sync/async_open_task.hpp
  src/realm/sync/client.cpp
  src/realm/sync/noinst/client_history_impl.cpp
  src/realm/sync/noinst/client_history_impl.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/sync/noinst/pending_bootstrap_store.cpp
  src/realm/sync/noinst/pending_bootstrap_store.hpp
  test/object-store/sync/app.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/sync/session/progress_notifications.cpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/object-store/util/sync/sync_test_utils.hpp
  test/test_sync_pending_bootstraps.cpp
Labels: cla: yes

#7880 RCORE-2065 use compressed string view for quick comparison if the leaf is compressed
  src/realm/query_engine.hpp
  src/realm/string_compressor.cpp
  src/realm/string_interner.cpp
  test/test_query.cpp
  test/test_string_compression.cpp
Labels: cla: yes, no-changelog

#7873 Add get local schema version to the C-API
  CHANGELOG.md
  src/realm.h
  src/realm/object-store/c_api/schema.cpp
  test/object-store/c_api/c_api.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7874 RCORE-2190 Sync client can crash if a session is resumed before UNBIND message finishes sending
  CHANGELOG.md
  src/realm/sync/noinst/client_impl_base.hpp
  test/object-store/sync/client_reset.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/object-store/util/sync/sync_test_utils.hpp
Labels: cla: yes

#7891 RCORE-2201 Add an implementation for the realm_app_config_get_sync_client_config() function in the Core CAPI
  CHANGELOG.md
  src/realm.h
  src/realm/object-store/c_api/app.cpp
  src/realm/object-store/c_api/sync.cpp
  src/realm/object-store/c_api/types.hpp
  test/object-store/c_api/c_api.cpp
Labels: cla: yes

#7840 RCORE-1974 Add tests for role/permissions changed during client reset
  src/realm/sync/config.hpp
  test/object-store/sync/flx_role_change.cpp
  test/object-store/util/sync/sync_test_utils.hpp
Labels: cla: yes, no-changelog

#7897 RCORE-2203 Merge Role Changes feature branch into Core master
  CHANGELOG.md
  dependencies.yml
  evergreen/config.yml
  src/realm/object-store/sync/sync_session.hpp
  src/realm/sync/client.cpp
  src/realm/sync/config.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/sync/noinst/pending_bootstrap_store.cpp
  src/realm/sync/noinst/protocol_codec.hpp
  src/realm/sync/protocol.hpp
  src/realm/sync/tools/apply_to_state_command.cpp
  test/object-store/CMakeLists.txt
  test/object-store/sync/flx_role_change.cpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/util/sync/baas_admin_api.cpp
  test/object-store/util/sync/baas_admin_api.hpp
  test/object-store/util/sync/flx_sync_harness.hpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/object-store/util/sync/sync_test_utils.hpp
  test/object-store/util/test_utils.hpp
Labels: cla: yes

#7859 RCORE-2129 Do not send empty upload messages if there are no downloads to ack
  CHANGELOG.md
  src/realm/sync/noinst/client_impl_base.cpp
  test/object-store/sync/flx_sync.cpp
Labels: cla: yes

#7900 Fix bad merge
  CHANGELOG.md
Labels: cla: yes, no-changelog, no-jira-ticket

#7906 RCORE-2204: Use accepting_clients key to check for initial sync completion in flx tests
  test/object-store/sync/flx_role_change.cpp
  test/object-store/util/sync/baas_admin_api.cpp
  test/object-store/util/sync/baas_admin_api.hpp
  test/object-store/util/sync/sync_test_utils.cpp
Labels: cla: yes, no-changelog

#7911 RCORE-2208 Regenerate testing certificates
  certificate-authority/certs/dns-chain.crt.pem
  certificate-authority/certs/dns-checked-server.crt.pem
  certificate-authority/certs/dns-checked-server.csr.pem
  certificate-authority/certs/dns-checked-server.key.pem
  certificate-authority/certs/ip-chain.crt.pem
  certificate-authority/certs/ip-server.crt.pem
  certificate-authority/certs/ip-server.csr.pem
  certificate-authority/certs/ip-server.key.pem
  certificate-authority/certs/localhost-chain.crt.cer
  certificate-authority/certs/localhost-chain.crt.pem
  certificate-authority/certs/localhost-server.crt.pem
  certificate-authority/certs/localhost-server.csr.pem
  certificate-authority/certs/localhost-server.key.pem
  certificate-authority/root-ca/crt.pem
  certificate-authority/root-ca/csr.pem
  certificate-authority/root-ca/db/ca.crt.srl
  certificate-authority/root-ca/db/ca.db
  certificate-authority/root-ca/key.pem
  certificate-authority/signing-ca/crt.pem
  certificate-authority/signing-ca/csr.pem
  certificate-authority/signing-ca/db/ca.crt.srl
  certificate-authority/signing-ca/db/ca.db
  certificate-authority/signing-ca/key.pem
  test/test_sync.cpp
Labels: cla: yes

#7917 RCORE-2210 Remove unused websocket too new/old errors
  CHANGELOG.md
  src/realm/error_codes.h
  src/realm/sync/network/default_socket.cpp
  src/realm/sync/network/websocket.cpp
  src/realm/sync/network/websocket_error.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/server/server.cpp
Labels: cla: yes

#7915 RCORE-2205 Remove unused changeset compaction code
  Package.swift
  src/realm/sync/CMakeLists.txt
  src/realm/sync/client_base.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/sync/noinst/compact_changesets.cpp
  src/realm/sync/noinst/compact_changesets.hpp
  src/realm/sync/noinst/server/server.cpp
  src/realm/sync/noinst/server/server.hpp
  src/realm/sync/noinst/server/server_history.cpp
  src/realm/sync/noinst/server/server_history.hpp
  test/CMakeLists.txt
  test/peer.hpp
  test/sync_fixtures.hpp
  test/test_compact_changesets.cpp
  test/test_embedded_objects.cpp
  test/test_sync.cpp
  test/test_transform.cpp
Labels: cla: yes, no-changelog

#7919 Fix intermittent failure of the role change client reset tests
  test/object-store/sync/flx_role_change.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7894 RCORE-2200: Fix switch_user and get_profile during log_in_with_credentials
  CHANGELOG.md
  src/realm/object-store/sync/app.cpp
  test/object-store/sync/app.cpp
Labels: cla: yes

#7849 RCORE-2187 Prefix sync connection log messages with co_id when possible
  CHANGELOG.md
  src/realm/sync/client.cpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/util/logger.hpp
  test/object-store/sync/app.cpp
  test/object-store/util/test_file.cpp
  test/object-store/util/test_file.hpp
Labels: cla: yes

#7813 RCORE-2171 Add testing mode where baas integration tests always start out talking to the wrong base url
  evergreen/config.yml
  test/object-store/sync/app.cpp
  test/object-store/util/sync/baas_admin_api.cpp
  test/object-store/util/sync/baas_admin_api.hpp
  test/object-store/util/sync/redirect_server.hpp
Labels: cla: yes, no-changelog

#7927 RCORE-2202 Fix asan failure in schema migration tests
  test/object-store/sync/flx_schema_migration.cpp
Labels: cla: yes, no-changelog

#7922 RCORE-2127 Do not report compensating write errors multiple times
  CHANGELOG.md
  src/realm/sync/noinst/client_impl_base.hpp
  test/object-store/sync/flx_sync.cpp
Labels: cla: yes

#7916 RCORE-1992 Add emscripten debug/release compile tasks to evergreen
  CHANGELOG.md
  evergreen/config.yml
  src/realm/alloc_slab.hpp
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/app.hpp
  src/realm/sync/instruction_applier.cpp
  src/realm/util/file.cpp
  test/util/CMakeLists.txt
  tools/cross_compile.sh
Labels: cla: yes

#7862 RCORE-2191 Add support for multi-process subscription state change notifications
  CHANGELOG.md
  src/realm/sync/client.cpp
  src/realm/sync/noinst/client_history_impl.cpp
  src/realm/sync/noinst/client_history_impl.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/sync/noinst/client_reset.cpp
  src/realm/sync/noinst/client_reset.hpp
  src/realm/sync/noinst/client_reset_operation.cpp
  src/realm/sync/noinst/client_reset_operation.hpp
  src/realm/sync/noinst/pending_bootstrap_store.cpp
  src/realm/sync/noinst/pending_bootstrap_store.hpp
  src/realm/sync/subscriptions.cpp
  src/realm/sync/subscriptions.hpp
  test/object-store/sync/flx_sync.cpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/test_client_reset.cpp
  test/test_sync_pending_bootstraps.cpp
  test/test_sync_subscriptions.cpp
  test/util/unit_test.hpp
Labels: cla: yes

#7937 RCORE-1990 Get exact parity with Jenkins for UWP builders in evg
  evergreen/config.yml
Labels: cla: yes, no-changelog
