Repository realm/realm-core, pull requests merged in 2024-06, with the labels that each got.

#7766 RCORE-2151 Fix race in schema migration tests
  test/object-store/sync/flx_schema_migration.cpp
Labels: cla: yes, no-changelog

#7761 RCORE-2150 Include originating client reset error message when reporting auto client reset failures
  CHANGELOG.md
  src/realm/object-store/sync/sync_session.cpp
  src/realm/object-store/sync/sync_session.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  test/object-store/sync/flx_sync.cpp
  test/test_client_reset.cpp
Labels: cla: yes

#7770 Fix XCode warning after 'notifications-fuzzer' directory was removed
  Package.swift
Labels: cla: yes, no-changelog, no-jira-ticket

#7542 RCORE-2063 Fix some client resets potentially failing with AutoClientResetFailed if a new client reset condition occurred before the first one completed
  CHANGELOG.md
  src/realm/sync/client.cpp
  src/realm/sync/config.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/sync/noinst/client_reset.cpp
  test/object-store/sync/flx_migration.cpp
  test/object-store/util/test_utils.hpp
Labels: cla: yes

#7769 RCORE-2110 Remove references to stitch in access token parsing
  CHANGELOG.md
  src/realm/sync/noinst/server/access_token.cpp
  test/stitch_private.pem
  test/stitch_public.pem
  test/test_sync_auth.cpp
Labels: cla: yes

#7758 RCORE-1985 Run core tests on ios Simulator in evergreen
  CHANGELOG.md
  evergreen/config.yml
  src/external/bson/CMakeLists.txt
  tools/run-in-simulator.sh
Labels: cla: yes

#7734 RCORE-2152 Don't emit transaction log instructions for mutations on newly-created objects
  CHANGELOG.md
  src/realm/exec/realm_trawler.cpp
  src/realm/replication.cpp
  src/realm/replication.hpp
  src/realm/sync/noinst/pending_bootstrap_store.cpp
  src/realm/table.cpp
  src/realm/table.hpp
  test/object-store/transaction_log_parsing.cpp
  test/test_replication.cpp
  test/test_table_helper.hpp
Labels: cla: yes

#7776 Revert "Disable replication when writing to the pending bootstrap store"
  src/realm/sync/noinst/pending_bootstrap_store.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7775 Add a check to verify the base commit build status in the release process
  .github/workflows/prepare-release.yml
  .gitignore
  tools/release-init.sh
Labels: cla: yes, no-changelog, no-jira-ticket

#7668 RCORE-2094 Compressing Integer Arrays
  Package.swift
  evergreen/config.yml
  src/realm/CMakeLists.txt
  src/realm/alloc_slab.cpp
  src/realm/array.cpp
  src/realm/array.hpp
  src/realm/array_aggregate_optimizations.cpp
  src/realm/array_blobs_small.cpp
  src/realm/array_blobs_small.hpp
  src/realm/array_direct.hpp
  src/realm/array_integer.cpp
  src/realm/array_integer.hpp
  src/realm/array_integer_tpl.hpp
  src/realm/array_mixed.cpp
  src/realm/array_unsigned.cpp
  src/realm/array_unsigned.hpp
  src/realm/array_with_find.cpp
  src/realm/array_with_find.hpp
  src/realm/group.cpp
  src/realm/group.hpp
  src/realm/group_writer.cpp
  src/realm/group_writer.hpp
  src/realm/impl/array_writer.hpp
  src/realm/impl/output_stream.cpp
  src/realm/impl/output_stream.hpp
  src/realm/integer_compressor.cpp
  src/realm/integer_compressor.hpp
  src/realm/integer_flex_compressor.cpp
  src/realm/integer_flex_compressor.hpp
  src/realm/integer_packed_compressor.cpp
  src/realm/integer_packed_compressor.hpp
  src/realm/node.cpp
  src/realm/node.hpp
  src/realm/node_header.hpp
  src/realm/obj.cpp
  src/realm/query_conditions.hpp
  src/realm/query_engine.hpp
  src/realm/query_state.hpp
  src/realm/table.hpp
  test/benchmark-common-tasks/main.cpp
  test/object-store/results.cpp
  test/test_array.cpp
  test/test_array_integer.cpp
  test/test_group.cpp
  test/test_links.cpp
  test/test_list.cpp
  test/test_query.cpp
  test/test_shared.cpp
  test/test_table.cpp
  test/test_unresolved_links.cpp
Labels: cla: yes, no-changelog

#7698 RCORE-2141 RCORE-2142 Clean up a bunch of old encryption cruft
  CHANGELOG.md
  src/realm/alloc.cpp
  src/realm/alloc.hpp
  src/realm/alloc_slab.cpp
  src/realm/alloc_slab.hpp
  src/realm/db.cpp
  src/realm/db.hpp
  src/realm/exec/realm_decrypt.cpp
  src/realm/group.cpp
  src/realm/group_writer.cpp
  src/realm/group_writer.hpp
  src/realm/node_header.hpp
  src/realm/object-store/impl/realm_coordinator.cpp
  src/realm/object-store/impl/realm_coordinator.hpp
  src/realm/query_engine.hpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/sync/noinst/server/server.cpp
  src/realm/sync/tools/print_changeset.cpp
  src/realm/tokenizer.cpp
  src/realm/transaction.cpp
  src/realm/util/aes_cryptor.hpp
  src/realm/util/encrypted_file_mapping.cpp
  src/realm/util/encrypted_file_mapping.hpp
  src/realm/util/file.cpp
  src/realm/util/file.hpp
  src/realm/util/file_mapper.cpp
  src/realm/util/file_mapper.hpp
  src/realm/util/load_file.cpp
  src/realm/util/load_file.hpp
  src/realm/util/safe_int_ops.hpp
  src/realm/utilities.hpp
  test/fuzz_group.cpp
  test/object-store/sync/client_reset.cpp
  test/object-store/sync/metadata.cpp
  test/object-store/sync/sync_manager.cpp
  test/object-store/thread_safe_reference.cpp
  test/object-store/util/sync/baas_admin_api.cpp
  test/realm-fuzzer/fuzz_configurator.cpp
  test/realm-fuzzer/fuzz_configurator.hpp
  test/test_all.cpp
  test/test_alloc.cpp
  test/test_compaction.cpp
  test/test_encrypted_file_mapping.cpp
  test/test_file.cpp
  test/test_group.cpp
  test/test_json.cpp
  test/test_shared.cpp
  test/test_transactions.cpp
  test/test_transform.cpp
  test/test_upgrade_database.cpp
  test/test_util_logger.cpp
  test/tsan.suppress
  test/util/spawned_process.cpp
  test/util/test_path.hpp
Labels: cla: yes, no-jira-ticket

#7786 Fix realm-benchmark-larger compilation
  test/benchmark-larger/main.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7782 Use environment in make-release.yml
  .github/workflows/make-release.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#7772 Optimize IntegerNode::find_first_local
  src/realm/array.hpp
  src/realm/array_integer_tpl.hpp
  src/realm/query_engine.hpp
  test/test_query.cpp
  test/util/test_path.cpp
Labels: cla: yes

#7733 handling exception better while creating fuzzer configuration
  test/realm-fuzzer/fuzz_engine.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7787 The GHA release script requires a token in the environment
  .github/workflows/prepare-release.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#7790 generate next changelog section
  CHANGELOG.md
Labels: cla: yes, no-jira-ticket

#7789 Fix several valgrind failures
  CHANGELOG.md
  src/realm/util/encrypted_file_mapping.cpp
  test/test_group.cpp
  test/valgrind.suppress
Labels: cla: yes, no-jira-ticket

#7723 RCORE-2135 Make AsyncOpenTask wait until all pending subscriptions finish bootstrapping
  CHANGELOG.md
  src/realm/object-store/impl/realm_coordinator.cpp
  src/realm/object-store/sync/async_open_task.cpp
  src/realm/object-store/sync/async_open_task.hpp
  test/object-store/sync/flx_sync.cpp
Labels: cla: yes

#7759 Improve FlexCompressor::find_all
  src/realm/integer_flex_compressor.cpp
  src/realm/integer_flex_compressor.hpp
  src/realm/query_conditions.hpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7773 RCORE-2149 Restore behavior of Sync_UploadDownloadProgress_1 test
  test/test_sync.cpp
Labels: cla: yes, no-changelog

#7802 RCORE-2166 Fix building with Xcode 16
  CHANGELOG.md
  CMakeLists.txt
  Package.swift
  evergreen/config.yml
  src/CMakeLists.txt
  src/realm/util/time.hpp
  test/benchmark-larger/main.cpp
  test/test_util_file.cpp
  tools/cmake/xcode.toolchain.cmake
Labels: cla: yes

#7806 RCORE-2153: Fix issue when clearing a Lst<Mixed> in an upgraded file
  CHANGELOG.md
  src/realm/array_mixed.cpp
Labels: cla: yes

#7791 RCORE-2096 Trim trailing slashes from base urls to prevent 404 errors
  CHANGELOG.md
  src/realm/object-store/sync/app.cpp
  test/object-store/sync/app.cpp
Labels: cla: yes

#7797 [bindgen] Expose `Obj::add_int()`
  CHANGELOG.md
  bindgen/spec.yml
Labels: cla: yes, no-jira-ticket

#7807 No Unique PTRs for `string interner` and `string compressor`
  src/realm/array.cpp
  src/realm/array.hpp
  src/realm/array_string.cpp
  src/realm/node.hpp
  src/realm/string_compressor.cpp
  src/realm/string_compressor.hpp
  src/realm/string_interner.cpp
  src/realm/string_interner.hpp
  src/realm/table.cpp
  test/object-store/sync/client_reset.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7818 update release process documentation
  doc/development/how-to-release.md
Labels: cla: yes, no-changelog, no-jira-ticket

#7810 RCORE-2168: Replicate clear instruction unconditionally
  CHANGELOG.md
  src/realm/dictionary.cpp
  src/realm/list.cpp
  src/realm/list.hpp
  test/object-store/object.cpp
  test/test_sync.cpp
Labels: cla: yes

#7780 RCORE-2155 Store FLX download progress in the Realm file
  CHANGELOG.md
  src/realm/sync/client.cpp
  src/realm/sync/history.hpp
  src/realm/sync/noinst/client_history_impl.cpp
  src/realm/sync/noinst/client_history_impl.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/sync/noinst/pending_bootstrap_store.cpp
  src/realm/sync/noinst/pending_bootstrap_store.hpp
  src/realm/sync/noinst/protocol_codec.hpp
  src/realm/sync/noinst/server/server_history.hpp
  src/realm/sync/protocol.hpp
  src/realm/sync/tools/apply_to_state_command.cpp
  src/realm/sync/transform.cpp
  test/object-store/benchmarks/client_reset.cpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/test_client_reset.cpp
  test/test_sync.cpp
Labels: cla: yes

#7819 Revert "RCORE-2168: Replicate clear instruction unconditionally (#7810)"
  CHANGELOG.md
  src/realm/dictionary.cpp
  src/realm/list.cpp
  src/realm/list.hpp
  test/object-store/object.cpp
  test/test_sync.cpp
Labels: cla: yes

#7804 RCORE-2162: Add compression of strings in Mixed, Lst<String> and Dictionary
  src/realm/array_backlink.cpp
  src/realm/array_mixed.cpp
  src/realm/array_mixed.hpp
  src/realm/array_string.cpp
  src/realm/array_string.hpp
  src/realm/bplustree.hpp
  src/realm/cluster.cpp
  src/realm/cluster_tree.cpp
  src/realm/collection.cpp
  src/realm/collection.hpp
  src/realm/dictionary.cpp
  src/realm/impl/array_writer.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  src/realm/obj.cpp
  src/realm/query_expression.hpp
  src/realm/set.hpp
  src/realm/table.cpp
  src/realm/table.hpp
  src/realm/to_json.cpp
  test/object-store/sync/client_reset.cpp
  test/test_lang_bind_helper.cpp
  test/test_list.cpp
  test/test_query.cpp
Labels: cla: yes

#7824 RCORE-2172 Fix race condition in "unregister connection change listener" test while listener is being unregistered
  test/object-store/sync/session/connection_change_notifications.cpp
Labels: cla: yes, no-changelog

#7845 RCORE-2184 Fix util::FlatMap to use Compare to check equality as well as ordering
  CHANGELOG.md
  src/realm/util/flat_map.hpp
  test/test_util_flat_map.cpp
Labels: cla: yes

#7844 RCORE-2183 Fix compacting a Realm file using the existing encryption key
  CHANGELOG.md
  src/realm/db.cpp
  src/realm/db.hpp
  src/realm/sync/noinst/server/server.hpp
  test/sync_fixtures.hpp
  test/test_shared.cpp
  test/test_sync.cpp
  test/util/crypt_key.cpp
  test/util/crypt_key.hpp
Labels: cla: yes

#7851 RCORE-2184 remove unused method now that FlatMap uses the < comparator
  src/realm/sync/noinst/client_reset_recovery.cpp
Labels: cla: yes, no-changelog

#7821 RCORE-2168: Replicate clear instruction unconditionally for nested collections
  CHANGELOG.md
  src/realm/dictionary.cpp
  src/realm/list.cpp
  test/test_sync.cpp
Labels: cla: yes

#7830 RCORE-2175 RCORE-2176 RCORE-2182 RCORE-2083 Fix several problems with object removal and links
  CHANGELOG.md
  src/realm/array_mixed.cpp
  src/realm/cluster.cpp
  src/realm/cluster.hpp
  src/realm/cluster_tree.cpp
  src/realm/cluster_tree.hpp
  src/realm/list.cpp
  src/realm/obj.cpp
  src/realm/query_engine.cpp
  src/realm/query_expression.hpp
  test/test_mixed_null_assertions.cpp
Labels: cla: yes
