Repository realm/realm-core, pull requests merged in 2024-08, with the labels that each got.

#7892 RCORE-2157 Avoid to decompress Strings while sorting them. Instead use fast comparison provided by the interner
  src/realm/array_mixed.cpp
  src/realm/array_mixed.hpp
  src/realm/array_string.cpp
  src/realm/obj.cpp
  src/realm/obj.hpp
  src/realm/path.hpp
  src/realm/sort_descriptor.cpp
  src/realm/sort_descriptor.hpp
  src/realm/string_compressor.cpp
  src/realm/string_data.hpp
  src/realm/string_interner.cpp
  src/realm/string_interner.hpp
  test/benchmark-common-tasks/main.cpp
  test/test_group.cpp
  test/test_query.cpp
  test/test_string_compression.cpp
  test/test_utf8.cpp
Labels: cla: yes, no-changelog

#7943 RCORE-2187 Fix a test failure when the default log level is too low
  test/object-store/sync/app.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7944 Only track pending client resets done by the same core version
  CHANGELOG.md
  src/realm/sync/CMakeLists.txt
  src/realm/sync/client.cpp
  src/realm/sync/noinst/client_reset.cpp
  src/realm/sync/noinst/client_reset.hpp
  src/realm/sync/noinst/migration_store.cpp
  src/realm/sync/noinst/pending_bootstrap_store.cpp
  src/realm/sync/noinst/pending_reset_store.cpp
  src/realm/sync/noinst/pending_reset_store.hpp
  src/realm/sync/noinst/sync_metadata_schema.cpp
  src/realm/sync/noinst/sync_metadata_schema.hpp
  src/realm/sync/subscriptions.cpp
  test/object-store/sync/client_reset.cpp
  test/test_client_reset.cpp
  test/test_sync_subscriptions.cpp
Labels: cla: yes, no-jira-ticket

#7899 RCORE-2223 reduce unnecessary table selections in replication
  CHANGELOG.md
  src/realm/replication.cpp
  src/realm/replication.hpp
  test/test_replication.cpp
Labels: cla: yes

#7949 RCORE-2224 clean up an unused read lock on subscription sets
  CHANGELOG.md
  src/realm/sync/subscriptions.cpp
  test/test_sync_subscriptions.cpp
Labels: cla: yes

#7898 Add `Obj::has_schema_property`
  bindgen/spec.yml
  src/realm/obj.cpp
  src/realm/obj.hpp
Labels: no-changelog, no-jira-ticket

#7960 More flexible schema work for RJS
  bindgen/spec.yml
  src/realm/object-store/collection.cpp
  src/realm/object-store/collection.hpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7934 RCORE-2213 Add CI builder that runs tests with log level set to all
  CHANGELOG.md
  evergreen/config.yml
  src/realm/sync/noinst/protocol_codec.cpp
  src/realm/util/serializer.cpp
  test/test_alloc.cpp
Labels: cla: yes

#7951 Remove HackClass
  src/realm/query_conditions.hpp
Labels: cla: yes

#7965 RCORE-2221 fix RQL BETWEEN regression for properties over links
  CHANGELOG.md
  src/realm/parser/driver.cpp
  test/test_parser.cpp
Labels: cla: yes

#7955 RCORE-1977 Empty reciprocal changesets lead to crashes or data divergence
  CHANGELOG.md
  src/realm/sync/noinst/client_history_impl.cpp
  src/realm/sync/transform.cpp
  test/test_sync.cpp
Labels: cla: yes

#7947 Upgrade to OpenSSL 3.3.1
  CHANGELOG.md
  dependencies.yml
  tools/cmake/armv7-linux-gnueabihf.toolchain.cmake
Labels: cla: yes

#7954 RCORE-2233 Reduce locking for StringInterner lookup and compare methods
  src/realm/string_interner.cpp
  src/realm/string_interner.hpp
Labels: cla: yes, no-changelog

#7967 RCORE-2232 Actually check for unuploaded changes in no_pending_local_changes()
  CHANGELOG.md
  src/realm/sync/noinst/client_history_impl.cpp
  test/object-store/realm.cpp
Labels: cla: yes

#7672 Replace TestAppSession close()/reopen() with scope based TestAppSession instance
  CHANGELOG.md
  test/object-store/c_api/c_api.cpp
  test/object-store/realm.cpp
  test/object-store/sync/app.cpp
  test/object-store/util/sync/flx_sync_harness.hpp
  test/object-store/util/test_file.cpp
  test/object-store/util/test_file.hpp
Labels: cla: yes, no-jira-ticket

#7979 Create test file in file-format 24
  test/test_upgrade_database.cpp
  test/test_upgrade_database_1000_24.realm
  test/test_upgrade_database_4_24.realm
Labels: cla: yes

#7984 RCORE-2178: Fix Realm2JSON help
  src/realm/exec/realm2json.cpp
Labels: cla: yes

#7986 RCORE-2167: C API: Fix empty keypath issue
  CHANGELOG.md
  src/realm/object-store/c_api/notifications.cpp
  test/object-store/c_api/c_api.cpp
Labels: cla: yes

#7987 RCORE-2061: Fix handling backlink column as last element in KeyPath
  CHANGELOG.md
  src/realm/object-store/impl/deep_change_checker.cpp
  src/realm/object-store/shared_realm.cpp
  test/object-store/object.cpp
Labels: cla: yes

#7973 Make Object::create accept addional properties
  src/realm/object-store/impl/object_accessor_impl.hpp
  src/realm/object-store/object_accessor.hpp
  test/object-store/object.cpp
Labels: cla: yes

#7989 Small fix for realm-trawler
  src/realm/exec/realm_trawler.cpp
Labels: cla: yes

#7990 Fix compile error
  src/realm/exec/realm_trawler.cpp
Labels: cla: yes

#7985 RCORE-2234 Crash in dart due to debug output when app is being torn down
  CHANGELOG.md
  src/realm/util/logger.cpp
Labels: cla: yes

#7774 Fix history command tool
  src/realm/sync/tools/hist_command.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7995 Updated bindgen spec and helpers
  bindgen/spec.yml
  bindgen/src/bound-model.ts
  bindgen/src/realm_helpers.h
Labels: cla: yes

#8000 RCORE-2242: Include pathname in exception thrown in File::rw_lock
  CHANGELOG.md
  src/realm/object-store/sync/impl/sync_file.hpp
  src/realm/util/file.cpp
  test/object-store/sync/file.cpp
  test/object-store/util/test_utils.cpp
  test/object-store/util/test_utils.hpp
Labels: cla: yes

#8010 RCORE-2180 Add basic translation of NSExceptions to Status
  CHANGELOG.md
  Package.swift
  src/realm/CMakeLists.txt
  src/realm/exceptions.cpp
  src/realm/exceptions.mm
  test/CMakeLists.txt
  test/test_nsexception.mm
Labels: cla: yes

#7996 RCORE-2222 Remove 308 redirect support from App/AppUser
  CHANGELOG.md
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/app.hpp
  src/realm/object-store/sync/app_utils.cpp
  src/realm/object-store/sync/app_utils.hpp
Labels: cla: yes
