Repository realm/realm-core, pull requests merged in 2024-04, with the labels that each got.

#7534 RCORE-2010 Update default base URL to new domain
  CHANGELOG.md
  src/realm/object-store/c_api/app.cpp
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/app.hpp
  test/object-store/c_api/c_api.cpp
  test/object-store/sync/app.cpp
Labels: cla: yes

#7537 RCORE-1980 Add unit test and changelog entry for replication bug
  CHANGELOG.md
  src/realm/list.hpp
  test/object-store/object.cpp
  test/test_transform.cpp
Labels: cla: yes

#7543 Handle exceptions correctly in Realm2JSON tool
  CHANGELOG.md
  src/realm/exec/realm2json.cpp
Labels: cla: yes

#7549 Reintroduce table name for links in xjson_plus format
  src/realm/to_json.cpp
  test/expected_xjson_plus_link.json
  test/expected_xjson_plus_linkdict1.json
  test/expected_xjson_plus_linklist1.json
  test/expected_xjson_plus_linkset1.json
Labels: cla: yes

#7532 Inlining main getters for ArrayEncode
  src/realm/alloc_slab.cpp
  src/realm/array.cpp
  src/realm/array_direct.hpp
  src/realm/array_encode.cpp
  src/realm/array_encode.hpp
  src/realm/array_flex.cpp
  src/realm/array_flex.hpp
  src/realm/array_packed.cpp
  src/realm/array_packed.hpp
  test/test_array.cpp
Labels: cla: yes

#7541 RCORE-2062 Update App debug statements to show final request URL before sending
  src/realm/object-store/sync/app.cpp
Labels: cla: yes, no-changelog

#7554 Use the "clang-format" provided by the system
  CHANGELOG.md
  bindgen/src/formatter.ts
  package.json
Labels: cla: yes

#7437 RCORE-2004 Make Realm::call_completion_callbacks() resilient to trasaction being deleted
  CHANGELOG.md
  src/realm/object-store/shared_realm.cpp
  test/object-store/realm.cpp
Labels: cla: yes

#7555 Follow-up to make #7124 target iPhone 11
  CHANGELOG.md
  src/realm/sync/noinst/client_impl_base.cpp
Labels: T-Internal, cla: yes, no-jira-ticket

#7557 prepare v14.5.0
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes, no-jira-ticket

#7559 Release v14.5.0
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes

#7563 Update documentation URL
  README.md
Labels: cla: yes, no-changelog, no-jira-ticket

#7567 update changelog after v14.5.0 release
  CHANGELOG.md
Labels: cla: yes, no-jira-ticket

#7552 RCORE-2070 Allow setting a security access group for the metadata realm keychain
  CHANGELOG.md
  bindgen/spec.yml
  src/realm.h
  src/realm/object-store/c_api/sync.cpp
  src/realm/object-store/impl/apple/keychain_helper.cpp
  src/realm/object-store/impl/apple/keychain_helper.hpp
  src/realm/object-store/sync/impl/sync_metadata.cpp
  src/realm/object-store/sync/impl/sync_metadata.hpp
  src/realm/object-store/sync/sync_manager.cpp
  src/realm/object-store/sync/sync_manager.hpp
  src/realm/sync/network/network_ssl.cpp
  src/realm/util/cf_str.hpp
  test/object-store/c_api/c_api.cpp
  test/object-store/sync/metadata.cpp
  test/object-store/sync/sync_manager.cpp
  test/object-store/sync/user.cpp
Labels: cla: yes

#7562 Destroy keys array when clearing a Lst<Mixed>
  CHANGELOG.md
  src/realm/array_mixed.cpp
  test/object-store/c_api/c_api.cpp
Labels: cla: yes

#7570 RCOCOA-2328 Add a privacy manifest to the Swift package
  CHANGELOG.md
  Package.swift
  src/realm/PrivacyInfo.xcprivacy
Labels: cla: yes

#7577 Add missing availability checks for SecCopyErrorMessageString
  src/realm/object-store/impl/apple/keychain_helper.cpp
  src/realm/sync/network/network_ssl.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7521 RCORE-2050 New Array Header support for compression
  src/realm/alloc.cpp
  src/realm/alloc.hpp
  src/realm/alloc_slab.cpp
  src/realm/array.cpp
  src/realm/array.hpp
  src/realm/array_basic_tpl.hpp
  src/realm/node.cpp
  src/realm/node.hpp
  src/realm/node_header.hpp
  test/test_alloc.cpp
Labels: cla: yes

#7579 RCORE-2080: Use the correct target conditional
  src/realm/object-store/impl/apple/keychain_helper.cpp
Labels: cla: yes, no-changelog

#7578 Use proper constructor when clearing links is nested collections
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/list.cpp
  src/realm/list.hpp
  test/test_sync.cpp
Labels: cla: yes

#7583 fix accidental use after free
  src/realm/sync/network/network_ssl.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7581 Fix encoding enum numbers
  src/realm/node_header.hpp
Labels: cla: yes

#7588 Fix compilation with `swift build`
  CHANGELOG.md
  Package.swift
  src/spm/PrivacyInfo.xcprivacy
  src/spm/dummy.mm
Labels: cla: yes, no-jira-ticket

#7569 RCORE-2029 Fix crash when removing dictionary key
  CHANGELOG.md
  src/realm/sync/instruction_applier.cpp
  test/test_transform.cpp
Labels: cla: yes

#7561 RCORE-2013 Allow non-streaming download callback on subsequent sync batches
  CHANGELOG.md
  src/realm/object-store/sync/sync_session.cpp
  src/realm/object-store/sync/sync_session.hpp
  src/realm/sync/client.cpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  test/object-store/sync/session/progress_notifications.cpp
Labels: cla: yes

#7535 RCORE-1969 Fix bundled encrypted Realm regression
  CHANGELOG.md
  src/realm/alloc.hpp
  src/realm/alloc_slab.cpp
  src/realm/util/encrypted_file_mapping.cpp
  src/realm/util/encrypted_file_mapping.hpp
  src/realm/util/file.cpp
  src/realm/util/file.hpp
  src/realm/util/file_mapper.cpp
  src/realm/util/file_mapper.hpp
  test/test_alloc.cpp
  test/test_encrypted_file_mapping.cpp
  test/test_shared.cpp
Labels: cla: yes

#7590 RCORE-2015 Add collection type to Clear instruction
  CHANGELOG.md
  src/realm/sync/changeset.cpp
  src/realm/sync/changeset.hpp
  src/realm/sync/changeset_encoder.cpp
  src/realm/sync/changeset_encoder.hpp
  src/realm/sync/changeset_parser.cpp
  src/realm/sync/instruction_applier.cpp
  src/realm/sync/instruction_replication.cpp
  src/realm/sync/instructions.hpp
  src/realm/sync/protocol.hpp
  src/realm/sync/transform.cpp
  test/object-store/sync/flx_sync.cpp
  test/test_changeset_encoding.cpp
Labels: cla: yes

#7592 RCORE-1493 Test roundtrip of collections in Mixed
  test/object-store/sync/flx_sync.cpp
  test/object-store/util/sync/baas_admin_api.cpp
Labels: cla: yes, no-changelog

#7599 Release/14.5.2
  CHANGELOG.md
  Package.swift
  dependencies.yml
  src/realm/sync/changeset.cpp
  src/realm/sync/changeset.hpp
  src/realm/sync/changeset_encoder.cpp
  src/realm/sync/changeset_encoder.hpp
  src/realm/sync/changeset_parser.cpp
  src/realm/sync/instruction_applier.cpp
  src/realm/sync/instruction_replication.cpp
  src/realm/sync/instructions.hpp
  src/realm/sync/protocol.hpp
  src/realm/sync/transform.cpp
  test/object-store/sync/flx_sync.cpp
  test/test_changeset_encoding.cpp
Labels: cla: yes

#7589 RCORE-1940 conditionally compile out the app services code
  CHANGELOG.md
  CMakeLists.txt
  Package.swift
  evergreen/config.yml
  src/realm.h
  src/realm/object-store/CMakeLists.txt
  src/realm/object-store/c_api/CMakeLists.txt
  src/realm/object-store/c_api/app.cpp
  src/realm/object-store/c_api/sync.cpp
  src/realm/object-store/sync/app_utils.cpp
  src/realm/object-store/sync/push_client.hpp
  src/realm/object-store/sync/sync_manager.hpp
  src/realm/object-store/sync/sync_user.hpp
  test/object-store/CMakeLists.txt
  test/object-store/c_api/c_api.cpp
  test/object-store/sync/session/session.cpp
  test/object-store/sync/sync_manager.cpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/object-store/util/sync/sync_test_utils.hpp
  test/object-store/util/test_file.cpp
  test/object-store/util/test_file.hpp
  test/object-store/util/unit_test_transport.cpp
Labels: cla: yes

#7602 Fix a race condition in Promise
  CHANGELOG.md
  src/realm/util/future.hpp
  test/test_util_future.cpp
Labels: cla: yes, no-jira-ticket

#7597 RCORE-2015 Merge rules for Clear instruction
  src/realm/sync/changeset_parser.cpp
  src/realm/sync/instruction_applier.cpp
  src/realm/sync/transform.cpp
  test/test_transform_collections_mixed.cpp
Labels: cla: yes, no-changelog

#7608 RCORE-2091 Fix Transaction::copy_to() for nested collection
  CHANGELOG.md
  src/realm/impl/copy_replication.cpp
  src/realm/obj.cpp
  src/realm/transaction.cpp
  test/test_shared.cpp
Labels: cla: yes

#7607 Schema migrations: Remove columns before removing the tables
  src/realm/group.cpp
  src/realm/group.hpp
  src/realm/sync/noinst/sync_schema_migration.cpp
  src/realm/table.cpp
  src/realm/table.hpp
  test/object-store/sync/flx_schema_migration.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7593 Bump baas
  dependencies.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#7598 Je/rcore 2055
  src/realm/array.cpp
  src/realm/array.hpp
  src/realm/array_integer.hpp
  src/realm/array_mixed.cpp
  src/realm/array_mixed.hpp
  src/realm/array_timestamp.cpp
  src/realm/array_timestamp.hpp
  src/realm/bplustree.cpp
  src/realm/bplustree.hpp
  src/realm/cluster.cpp
  src/realm/cluster.hpp
  src/realm/cluster_tree.cpp
  src/realm/cluster_tree.hpp
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/group.cpp
  src/realm/group.hpp
  src/realm/group_writer.cpp
  src/realm/impl/array_writer.hpp
  src/realm/node.hpp
  src/realm/node_header.hpp
  src/realm/table.cpp
  src/realm/table.hpp
Labels: cla: yes

#7564 RCORE-2055 Array Classification for enabling compression
  src/realm/array.cpp
  src/realm/array.hpp
  src/realm/array_integer.hpp
  src/realm/array_mixed.cpp
  src/realm/array_mixed.hpp
  src/realm/array_timestamp.cpp
  src/realm/array_timestamp.hpp
  src/realm/bplustree.cpp
  src/realm/bplustree.hpp
  src/realm/cluster.cpp
  src/realm/cluster.hpp
  src/realm/cluster_tree.cpp
  src/realm/cluster_tree.hpp
  src/realm/db.cpp
  src/realm/dictionary.cpp
  src/realm/dictionary.hpp
  src/realm/group.cpp
  src/realm/group.hpp
  src/realm/group_writer.cpp
  src/realm/impl/array_writer.hpp
  src/realm/node.hpp
  src/realm/node_header.hpp
  src/realm/spec.hpp
  src/realm/table.cpp
  src/realm/table.hpp
  src/realm/transaction.hpp
Labels: cla: yes

#7582 RNET-1131: optimize many OR'd terms on UUID/ObjectId queries
  CHANGELOG.md
  src/realm/parser/driver.cpp
  src/realm/query.cpp
  src/realm/query.hpp
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  test/benchmark-common-tasks/main.cpp
  test/test_query2.cpp
  test/test_types_helper.hpp
Labels: cla: yes

#7553 Do not require group in ClientHistory::update_from_ref_and_version
  CHANGELOG.md
  src/realm/sync/noinst/client_history_impl.cpp
  src/realm/sync/noinst/client_history_impl.hpp
  test/test_sync.cpp
Labels: cla: yes

#7475 RCORE-1984 update clang and prefer ARM64 to x86_64
  CHANGELOG.md
  evergreen/config.yml
Labels: cla: yes

#7619 modify errors_seen under lock to avoid race
  test/util/unit_test.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7617 Remove unused files
  Visual Studio/uwp_demo/App.xaml
  Visual Studio/uwp_demo/App.xaml.cpp
  Visual Studio/uwp_demo/App.xaml.h
  Visual Studio/uwp_demo/App1.sln
  Visual Studio/uwp_demo/App1.vcxproj
  Visual Studio/uwp_demo/App1.vcxproj.filters
  Visual Studio/uwp_demo/App1_TemporaryKey.pfx
  Visual Studio/uwp_demo/Assets/LockScreenLogo.scale-200.png
  Visual Studio/uwp_demo/Assets/SplashScreen.scale-200.png
  Visual Studio/uwp_demo/Assets/Square150x150Logo.scale-200.png
  Visual Studio/uwp_demo/Assets/Square44x44Logo.scale-200.png
  Visual Studio/uwp_demo/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  Visual Studio/uwp_demo/Assets/StoreLogo.png
  Visual Studio/uwp_demo/Assets/Wide310x150Logo.scale-200.png
  Visual Studio/uwp_demo/MainPage.xaml
  Visual Studio/uwp_demo/MainPage.xaml.cpp
  Visual Studio/uwp_demo/MainPage.xaml.h
  Visual Studio/uwp_demo/Package.appxmanifest
  Visual Studio/uwp_demo/pch.cpp
  Visual Studio/uwp_demo/pch.h
  external/CMakeLists.txt
  external/generated/empty.cpp
Labels: cla: yes

#7478 Support assigning nested collections via templated API
  CHANGELOG.md
  src/realm/collection.cpp
  src/realm/list.hpp
  src/realm/object-store/dictionary.hpp
  src/realm/object-store/impl/object_accessor_impl.hpp
  src/realm/object-store/list.hpp
  src/realm/object-store/object_accessor.hpp
  src/realm/object-store/results.hpp
  test/object-store/dictionary.cpp
  test/object-store/object.cpp
  test/object-store/primitive_list.cpp
Labels: cla: yes

#7618 RCORE-2097 Upgrade macos in evergreen to MacOS 14 building with Xcode 15
  CHANGELOG.md
  evergreen/config.yml
  test/object-store/CMakeLists.txt
  test/test_file.cpp
  test/util/spawned_process.cpp
Labels: cla: yes

#7623 [bindgen] follow up to #7300
  bindgen/spec.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#7632 RCORE-2100: Restore ability to create test users
  CHANGELOG.md
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/app.hpp
Labels: cla: yes

#7528 RCORE-2060 Enabling 'cancel_waits_on_nonfatal_error' does not cancel waits during location update while offline
  CHANGELOG.md
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/sync_session.cpp
  test/object-store/realm.cpp
  test/object-store/util/sync/baas_admin_api.cpp
  test/object-store/util/test_file.cpp
  test/object-store/util/test_file.hpp
Labels: cla: yes

#7631 Prepare release
  CHANGELOG.md
  Package.swift
  bindgen/spec.yml
  bindgen/src/realm_helpers.h
  dependencies.yml
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/sync_session.cpp
  test/object-store/realm.cpp
  test/object-store/util/sync/baas_admin_api.cpp
  test/object-store/util/test_file.cpp
  test/object-store/util/test_file.hpp
Labels: cla: yes, no-jira-ticket

#7635 RCORE-1991 Add small BPNode/no encryption builders
  evergreen/config.yml
  src/realm/CMakeLists.txt
  src/realm/util/encrypted_file_mapping.cpp
  test/object-store/sync/metadata.cpp
  test/test_sync_history_migration.cpp
  test/test_sync_subscriptions.cpp
Labels: cla: yes, no-changelog

#7639 merge release 14.6.0
  CHANGELOG.md
  Package.swift
  bindgen/spec.yml
  bindgen/src/realm_helpers.h
  dependencies.yml
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/sync_session.cpp
  test/object-store/realm.cpp
  test/object-store/util/sync/baas_admin_api.cpp
  test/object-store/util/test_file.cpp
  test/object-store/util/test_file.hpp
Labels: cla: yes, no-jira-ticket

#7626 Add .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: cla: yes

#7628 RCORE-2098: Fix issue with OR of two IN queries
  CHANGELOG.md
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  test/test_parser.cpp
  test/test_query2.cpp
Labels: cla: yes

#7640 Fix building for Apple devices
  CHANGELOG.md
  CMakeLists.txt
Labels: cla: yes

#7615 glue code for CAPI custom user via callbacks
  CHANGELOG.md
  bindgen/spec.yml
  src/realm.h
  src/realm/object-store/c_api/app.cpp
  src/realm/object-store/c_api/sync.cpp
  src/realm/object-store/c_api/types.hpp
  src/realm/object-store/sync/app_user.cpp
  src/realm/object-store/sync/app_user.hpp
  src/realm/object-store/sync/sync_manager.hpp
  src/realm/object-store/sync/sync_user.hpp
  test/object-store/c_api/c_api.cpp
  test/object-store/util/test_file.hpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7648 Bump minimum deployment targets to the minimums supported by Xcode 15
  CHANGELOG.md
  Package.swift
  src/realm/object-store/impl/apple/keychain_helper.cpp
  src/realm/sync/network/network_ssl.cpp
  src/realm/util/compression.cpp
  src/realm/util/file_mapper.cpp
  src/realm/util/interprocess_condvar.hpp
  src/realm/util/terminate.cpp
  tools/cmake/xcode.toolchain.cmake
Labels: cla: yes, no-jira-ticket

#7651 Temporarily revert exfat changes
  evergreen/config.yml
Labels: cla: yes

#7646 Build with -Werror on CI
  CHANGELOG.md
  evergreen/config.yml
  src/external/IntelRDFPMathLib20U2/CMakeLists.txt
  src/external/bson/CMakeLists.txt
  src/external/bson/bson-macros.h
  src/external/bson/bson-types.h
  src/realm/object-store/object_store.cpp
  src/realm/object-store/sync/impl/app_metadata.cpp
  src/realm/object-store/sync/sync_manager.cpp
  src/realm/object-store/sync/sync_manager.hpp
  test/object-store/CMakeLists.txt
  test/object-store/benchmarks/main.cpp
  test/object-store/sync/client_reset.cpp
  test/object-store/util/test_file.cpp
  test/test_encrypted_file_mapping.cpp
Labels: cla: yes
