Repository realm/realm-core, pull requests merged in 2024-05, with the labels that each got.

#7558 Perf work query and decompression
  src/realm/alloc_slab.cpp
  src/realm/array.cpp
  src/realm/array.hpp
  src/realm/array_direct.hpp
  src/realm/array_mixed.cpp
  src/realm/cluster_tree.cpp
  src/realm/integer_compressor.cpp
  src/realm/integer_compressor.hpp
  src/realm/integer_flex_compressor.cpp
  src/realm/integer_flex_compressor.hpp
  src/realm/integer_packed_compressor.cpp
  src/realm/integer_packed_compressor.hpp
  src/realm/node.cpp
  src/realm/node.hpp
  src/realm/node_header.hpp
  src/realm/query_engine.hpp
  test/benchmark-common-tasks/main.cpp
  test/test_array_integer.cpp
Labels: cla: yes

#7650 RCORE-2102 Query in fixes
  CHANGELOG.md
  src/realm/query_engine.cpp
  src/realm/query_engine.hpp
  test/test_parser.cpp
  test/test_query2.cpp
Labels: cla: yes

#7658 core v14.6.1
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes

#7660 Core v14.6.1
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes

#7661 Forgot to add a commit with the release note.
  CHANGELOG.md
Labels: cla: yes

#7663 Prepare release v14.6.2
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes, no-jira-ticket

#7666 Merge release v14.6.2
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes, no-jira-ticket

#7665 [bindgen] fix signature of update_base_url
  bindgen/spec.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#7655 Also adapt argument list to target type
  src/realm/parser/driver.cpp
  test/object-store/c_api/c_api.cpp
  test/test_parser.cpp
Labels: cla: yes

#7671 RCORE-2112 Fix a deadlock when accessing current user from inside an App listener
  CHANGELOG.md
  src/realm/object-store/sync/app.cpp
  src/realm/object-store/sync/app.hpp
  test/object-store/sync/app.cpp
Labels: cla: yes

#7677 RCORE-2115 Fix multiple backlinks created by dictionary
  CHANGELOG.md
  src/realm/dictionary.cpp
  test/test_dictionary.cpp
Labels: cla: yes

#7653 Fix handling of collection in mixed. Adding support for Links + fix to prefix/suffix algo
  src/realm/object_converter.cpp
  src/realm/object_converter.hpp
  test/object-store/sync/client_reset.cpp
Labels: cla: yes, no-jira-ticket

#7679 Fix test failure
  test/object-store/sync/client_reset.cpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7680 RCORE-2108: Clear backlinks when object containing nested collections is deleted
  CHANGELOG.md
  src/realm/array_backlink.cpp
  src/realm/cluster.cpp
  src/realm/cluster.hpp
  src/realm/replication.cpp
  src/realm/replication.hpp
  src/realm/table.cpp
  test/test_list.cpp
Labels: cla: yes

#7480 RCORE-2120 Throw useful error messages if baasaas fails to start a container
  test/object-store/util/sync/baas_admin_api.cpp
Labels: cla: yes, no-changelog

#7683 RCORE-2030 Add full support for automatic client reset for collections in mixed
  CHANGELOG.md
  dependencies.yml
  src/realm/object_converter.cpp
  src/realm/object_converter.hpp
  src/realm/sync/changeset.cpp
  src/realm/sync/instruction_applier.cpp
  src/realm/sync/instruction_applier.hpp
  src/realm/sync/noinst/client_reset_recovery.cpp
  test/object-store/sync/client_reset.cpp
  test/object-store/sync/flx_sync.cpp
Labels: cla: yes

#7694 Preserve context flag when comitting BPlusTree
  src/realm/array.hpp
  src/realm/bplustree.cpp
Labels: cla: yes

#7571 RCORE-2076 Introducing bitfield iterator for accessing unaligned values for compressed arrays
  src/realm/array_direct.hpp
  src/realm/group_writer.cpp
  test/test_array.cpp
Labels: cla: yes

#7702 RCORE-2119 Bump sync protocol version for collections in Mixed
  src/realm/sync/protocol.hpp
  test/object-store/sync/flx_sync.cpp
Labels: cla: yes, no-changelog

#7704 Prepare release
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes

#7705 Release/14.7.0
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes

#7681 RCORE-2099 Restore progress notifier behavior when sync session is already caught up
  CHANGELOG.md
  src/realm/object-store/sync/sync_session.cpp
  src/realm/object-store/sync/sync_session.hpp
  src/realm/sync/client.cpp
  src/realm/sync/client.hpp
  test/object-store/sync/session/progress_notifications.cpp
  test/test_sync.cpp
Labels: cla: yes

#7710 Removed duplicate library warning when building realm2json
  src/realm/exec/CMakeLists.txt
Labels: cla: yes, no-changelog, no-jira-ticket

#7700 Upload also the realm file when the fuzzer fails
  evergreen/config.yml
Labels: cla: yes, no-changelog, no-jira-ticket

#7664 RCORE-2058 Adding clickbench importer and query tool for evaluating compression
  src/realm/array_direct.hpp
  src/realm/exec/CMakeLists.txt
  src/realm/exec/clickbench.cpp
  src/realm/exec/clickquery.cpp
  src/realm/node_header.hpp
  test/test_array.cpp
Labels: cla: yes

#7667 RCORE-2057 New builder for assessing that compression is working correctly
  CMakeLists.txt
  evergreen/config.yml
  src/realm/util/config.h.in
Labels: cla: yes

#7614 Add vendor support to Android blueprints
  Android.bp
  CHANGELOG.md
  src/realm/object-store/util/scheduler.cpp
  tools/generate-version-numbers-for-soong.sh
Labels: cla: yes, no-jira-ticket

#7696 Delete the old pre-c++11 Thread implementation
  CHANGELOG.md
  src/realm/util/thread.cpp
  src/realm/util/thread.hpp
  src/realm/util/thread_exec_guard.hpp
  test/test_lang_bind_helper.cpp
  test/test_shared.cpp
  test/test_thread.cpp
  test/util/thread_wrapper.hpp
  test/util/unit_test.cpp
Labels: cla: yes, no-jira-ticket

#7692 RCORE-1997 RCORE-2113 Add baas artifact generation to evergreen
  evergreen/config.yml
Labels: cla: yes

#7715 RCORE-2131: Don't throw immediately when convertion of string to number fails
  CHANGELOG.md
  src/realm/parser/driver.cpp
  test/test_parser.cpp
Labels: cla: yes

#7722 RCORE-2132 fix fuzzer bootstrap when encryption key is not provided
  test/realm-fuzzer/fuzz_configurator.cpp
Labels: cla: yes, no-changelog

#7566 RCORE-2134 automate the release process
  .github/workflows/make-release.yml
  .github/workflows/prepare-release.yml
  .gitignore
  doc/development/how-to-release.md
  tools/release-init.sh
  tools/release-tag.sh
Labels: cla: yes, no-changelog, no-jira-ticket

#7726 RCORE-2134 update scripts for CI
  tools/release-init.sh
Labels: cla: yes, no-changelog

#7727 RCORE-2134 GHA release script fixes
  .github/workflows/make-release.yml
  .github/workflows/prepare-release.yml
  tools/release-init.sh
Labels: cla: yes, no-changelog

#7728 Prepare for 14.8.0
  CHANGELOG.md
  Package.swift
  dependencies.yml
Labels: cla: yes, no-jira-ticket

#7731 Fix compilation of scheduler on Android
  src/realm/object-store/util/scheduler.cpp
Labels: no-changelog, no-jira-ticket

#7736 Use only one inderection when accessing compressed arrays.
  src/realm/array.cpp
  src/realm/array.hpp
  src/realm/array_aggregate_optimizations.cpp
  src/realm/array_with_find.cpp
  src/realm/array_with_find.hpp
  src/realm/cluster.hpp
  src/realm/cluster_tree.cpp
  src/realm/group.cpp
  src/realm/integer_compressor.cpp
  src/realm/integer_compressor.hpp
  src/realm/integer_flex_compressor.cpp
  src/realm/integer_flex_compressor.hpp
  src/realm/integer_packed_compressor.cpp
  src/realm/integer_packed_compressor.hpp
Labels: cla: yes

#7738 Add missing file to Android Blueprint
  Android.bp
  CHANGELOG.md
Labels: cla: yes, no-jira-ticket

#7721 Include '$set' in set of links
  src/realm/list.cpp
  src/realm/set.cpp
  test/expected_xjson_linkset1.json
  test/expected_xjson_plus_linkset1.json
Labels: cla: yes

#7742 RCORE-2140 Work around a VC++ bug in util::overload
  CHANGELOG.md
  src/realm/sync/changeset.cpp
  src/realm/util/overload.hpp
Labels: cla: yes

#7739 Small optimizations
  src/realm/array.hpp
  src/realm/integer_compressor.cpp
  src/realm/integer_compressor.hpp
  src/realm/integer_flex_compressor.cpp
  src/realm/integer_flex_compressor.hpp
Labels: cla: yes, no-changelog, no-jira-ticket

#7609 RCORE-2092 Simplify the SessionWrapper lifecycle a bit
  CHANGELOG.md
  src/realm/db.cpp
  src/realm/object-store/c_api/types.hpp
  src/realm/object-store/sync/impl/sync_client.hpp
  src/realm/object-store/sync/sync_session.cpp
  src/realm/sync/binding_callback_thread_observer.hpp
  src/realm/sync/client.cpp
  src/realm/sync/client.hpp
  src/realm/sync/network/default_socket.cpp
  src/realm/sync/network/default_socket.hpp
  src/realm/sync/network/network.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/util/future.hpp
  src/realm/util/scope_exit.hpp
  test/benchmark-sync/bench_transform.cpp
  test/sync_fixtures.hpp
  test/test_client_reset.cpp
  test/test_sync.cpp
  test/test_util_scope_exit.cpp
Labels: cla: yes

#7748 Getting rid of some glue code
  src/realm/array_direct.hpp
  src/realm/integer_compressor.hpp
  src/realm/integer_flex_compressor.hpp
  src/realm/integer_packed_compressor.hpp
  src/realm/query_conditions.hpp
  src/realm/query_state.hpp
  test/test_array.cpp
Labels: cla: yes

#7719 RCORE-2148 Reconnect Hang Analyzer to evergreen
  evergreen/config.yml
  evergreen/hang_analyzer/requirements.txt
Labels: cla: yes

#7755 Add missing flag to Android blueprint
  Android.bp
  CHANGELOG.md
  src/realm/mixed.cpp
Labels: cla: yes, no-jira-ticket

#7649 RCORE-1386 Track client reset reason in table that detects client reset cycles
  CHANGELOG.md
  Package.swift
  src/realm/db.hpp
  src/realm/object-store/sync/sync_session.cpp
  src/realm/object-store/sync/sync_session.hpp
  src/realm/sync/CMakeLists.txt
  src/realm/sync/client.cpp
  src/realm/sync/client_base.hpp
  src/realm/sync/noinst/client_history_impl.cpp
  src/realm/sync/noinst/client_history_impl.hpp
  src/realm/sync/noinst/client_impl_base.cpp
  src/realm/sync/noinst/client_impl_base.hpp
  src/realm/sync/noinst/client_reset.cpp
  src/realm/sync/noinst/client_reset.hpp
  src/realm/sync/noinst/client_reset_operation.cpp
  src/realm/sync/noinst/client_reset_operation.hpp
  src/realm/sync/noinst/client_reset_recovery.cpp
  src/realm/sync/noinst/migration_store.cpp
  src/realm/sync/noinst/pending_bootstrap_store.cpp
  src/realm/sync/noinst/pending_reset_store.cpp
  src/realm/sync/noinst/pending_reset_store.hpp
  src/realm/sync/noinst/sync_metadata_schema.cpp
  src/realm/sync/noinst/sync_metadata_schema.hpp
  src/realm/sync/subscriptions.cpp
  test/object-store/sync/app.cpp
  test/object-store/sync/client_reset.cpp
  test/object-store/util/sync/sync_test_utils.cpp
  test/test_client_reset.cpp
  test/util/compare_groups.cpp
Labels: cla: yes

#7753 RCORE-2145: Output InRealmHistory when compacting
  CHANGELOG.md
  src/realm/group.cpp
  test/test_shared.cpp
Labels: cla: yes

#7474 RCORE-1990 Add UWP windows builder
  evergreen/config.yml
Labels: cla: yes

#7695 Delete long-obsolete tests and benchmarks
  test/CMakeLists.txt
  test/benchmark-common-tasks-ios/Base.lproj/LaunchScreen.xib
  test/benchmark-common-tasks-ios/Base.lproj/Main.storyboard
  test/benchmark-common-tasks-ios/Images.xcassets/AppIcon.appiconset/Contents.json
  test/benchmark-common-tasks-ios/Info.plist
  test/benchmark-common-tasks-ios/ViewController.h
  test/benchmark-common-tasks-ios/ViewController.mm
  test/benchmark-common-tasks-ios/main.m
  test/benchmark-history-types/.gitignore
  test/benchmark-history-types/main.cpp
  test/benchmark-index/mkindex.cpp
  test/benchmark-insert-add/.gitignore
  test/benchmark-insert-add/add_insert.cpp
  test/benchmark-insert-add/batched.sh
  test/benchmark-insert-add/performance.gnuplot
  test/benchmark-insert-add/run.sh
  test/benchmark-prealloc/.gitignore
  test/benchmark-prealloc/main.cpp
  test/benchmark-row-accessor/.gitignore
  test/benchmark-row-accessor/main.cpp
  test/benchmark-transaction/run-benchmarks.sh
  test/benchmark-transaction/transact.cpp
  test/object-store/CMakeLists.txt
  test/object-store/notifications-fuzzer/CMakeLists.txt
  test/object-store/notifications-fuzzer/command_file.cpp
  test/object-store/notifications-fuzzer/command_file.hpp
  test/object-store/notifications-fuzzer/fuzz-sorted-linkview.cpp
  test/object-store/notifications-fuzzer/fuzz-sorted-query.cpp
  test/object-store/notifications-fuzzer/fuzz-unsorted-linkview.cpp
  test/object-store/notifications-fuzzer/fuzz-unsorted-query.cpp
  test/object-store/notifications-fuzzer/fuzzer.cpp
  test/object-store/notifications-fuzzer/input-lv/0
  test/object-store/notifications-fuzzer/input/0
  test/object-store/notifications-fuzzer/input/1
  test/performance/.gitignore
  test/performance/matrix.cpp
  test/protocol_compat/.gitignore
  test/protocol_compat/test.py
  test/simple-connection/.gitignore
  test/simple-connection/main.cpp
  test/test_client_reset_query_based.cpp
  test/test_optional.cpp
  test/test_table.cpp
  test/unit-tests-ios/Base.lproj/LaunchScreen.xib
  test/unit-tests-ios/Base.lproj/Main.storyboard
  test/unit-tests-ios/Images.xcassets/AppIcon.appiconset/Contents.json
  test/unit-tests-ios/Info.plist
  test/unit-tests-ios/ViewController.h
  test/unit-tests-ios/ViewController.mm
  test/unit-tests-ios/main.m
Labels: cla: yes, no-changelog, no-jira-ticket

#7730 RCORE-2134 touch up the GHA release process based on the first full run
  .github/workflows/make-release.yml
  .github/workflows/prepare-release.yml
  doc/development/how-to-release.md
  tools/release-init.sh
Labels: cla: yes, no-changelog

#7763 RCORE-2134 fix output syntax
  .github/workflows/make-release.yml
  .github/workflows/prepare-release.yml
Labels: cla: yes, no-changelog
